### ISSUE TITLE
Deleted and Muted Posts in feeds

### ISSUE THREAD

**Issue by dquick-freelance** [appdotnet/api-spec#102]
Currently (AFAIK) when a feed is requested on behalf os a user, the returned data set contains deleted posts, but does not contain posts that were written by users that the current user has muted. 

IMO this is a bug as it is not internally consistent - I believe filtering of deleted/muted posts should happen client-side (allowing for alternate display of such posts) but at the very least they should be handled similarly - either both returned or both not returned.

This issue could also be resolved via flags on the request to the endpoint along the lines of include_deleted and include_muted if that is preferable (and it probably is).

**Comment by mthurman** [comment]
I think the defaults make sense. If I'm muting someone, that's a signal that I really don't want to see what they said. If something is deleted, we include it so a client can still show a marker and maintain the integrity of the conversation.

Either way, we've added the flags so developers can choose: https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#general-parameters
