### ISSUE TITLE
Suggestion for returning a single post

### ISSUE THREAD

**Issue by ghost** [appdotnet/api-spec#104]
Hi,

When you return a post now it is not exactly the same as when you return multiple posts. The a single post is not in a counted [0] array which while not a big deal makes for clients dealing with it differently. Some may create a separate routine to handle it or like me push the array into a new counted array and null out the original, all so I can run it through the same foreach as I do for showing posts elsewhere.

Cheers,
Harold

**Comment by mthurman** [comment]
If you ask for a single object, you'll get a JSON object. If you ask for a list (even if it only has one item), you'll get a list. It's intentional that these behaviors are different and I think it would be confusing if it changed.
