### ISSUE TITLE
It would be useful to have an expiration time on a post

### ISSUE THREAD

**Issue by ammist** [appdotnet/api-spec#106]
For posts and status updates that have time-based component, it would be helpful to "expire" them.  For example,  "This coupon is valid till Sunday Sep 9" or "Justin Bieber is signing autographs at the Mall until 4 PM".

**Comment by abitgone** [comment]
Presumably the posts/updates would be marked as 'expired' rather than being physically deleted, and then expiry-aware clients would show them appropriately?

**Comment by mthurman** [comment]
This sounds like this belongs in an annotation and not the core api. I know annotations are kind of abstract at this point but I'm going to close this issue. This seems like it's useful for a very small subset of posts and so probably doesn't belong in the core Post object.

**Comment by ammist** [comment]
That makes sense.  What's the process for discussing a standard annotation
for this particular feature?  Or should we go ahead and create our own
formats?

**Comment by mthurman** [comment]
We're hoping to get back to annotations next week (this week has be lots of administrative stuff). For annotation formats that are really common, we'd like to define and standardize them in a 'wellknown' shared namespace (https://github.com/appdotnet/api-spec/blob/master/objects.md#post-annotations). But apps will also be able to define their own formats.

For an expiration time, I think ISO8601 has that covered pretty well.
