### ISSUE TITLE
Developers should have test accounts

### ISSUE THREAD

**Issue by beccadax** [appdotnet/api-spec#109]
I don't want to bother my followers with test messages, and at $50 a pop, new accounts aren't cheap. I'd love to have the ability to create a test account from my developer account. It doesn't even need to be visible from accounts other than my own, as long as the API is close enough for me to run ad-hoc and automated tests with it.

**Comment by abraham** [comment]
I would actually prefer to have a sandbox API we can thrash and not bother the regular users with data.

**Comment by kosso** [comment]
+1

**Comment by DuoSRX** [comment]
+1, we need a sandbox API.

**Comment by abitgone** [comment]
@abraham Spot on. A much better idea!

**Comment by tgvashworth** [comment]
@abraham Agreed, this'd be great.

**Comment by swhitley** [comment]
I'll toss out the idea of creating a localhost appliance if a sandbox isn't practical.

**Comment by jdscolam** [comment]
## Anything that makes the Authentication story better would help. I still don't see how this solves the client-side problems though.

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Shannon Whitley notifications@github.com wrote:

I'll toss out the idea of creating a localhost appliance if a sandbox isn't practical.

**Comment by sneakyness** [comment]
I'm definitely down to contribute to a localhost appliance. That's all I really do at work, create local "fakes" in place of real hardware to build up the rest of our stack with. 

It can be dangerous, but I feel that this platform is open and dedicated enough that it would be maintained pretty well by devs of all denominations.

**Comment by cgiffard** [comment]
Personally, I'd still like for a centrally available sandbox API to be provided. I'm considering adding App.net functionality into embedded devices certainly not capable of running their own VMs, and not guaranteed to be able to connect to a local appliance.

**Comment by FGRibreau** [comment]
+1 for the sandbox API

**Comment by jdscolam** [comment]
Big announcement! Rapptor authentications for #ADN are now available on GitHub and NuGet at http://bit.ly/P1P4yW. We have a functioning clearing house at http://rapptorapp.net. Ping me if you have any questions.  Huge thanks to @fwanicka for putting together the server-side #signalr hub.

**Comment by fwanicka** [comment]
+1 for the test accounts for developers. The sandbox is needed as well, but it won't help when I have to submit my app to the app store for approval and I have to provide them with an account they can use to try it out. You can time limit them, or whatever is necessary to prevent abuse, but I have already paid the developer fee. I shouldn't have to purchase additional accounts just for this.

**Comment by DaveWoodCom** [comment]
+1 for test accounts and a sandbox API.

**Comment by mthurman** [comment]
A sandbox is a longer term goal, but in the short term we have a test account that developers can use specifically for app reviews (this is _not_ a general testing account). For access, please email support@app.net.

**Comment by orianmarx** [comment]
We've offered additional accounts to developers for a minimal fee for a little while now: http://devblog.app.net/2012/10/27/developer-test-accounts/

I'm going to leave this thread open since we don't yet have a developer sandbox but is something we might still do.

**Comment by hybotix** [comment]
+1 on developer accounts _and_ sandbox. When we pony up $100.00/year for a developer account, we should get one test account with it at NO ADDITIONAL charge.

**Comment by berg** [comment]
Developer accounts should have a decent number of invites you can use to create new accounts for free, and, as mentioned above, you can get two more full-featured member accounts for $5/year.

Given that we now have perpetual free accounts via invites, I'm going to close this.
