### ISSUE TITLE
Images as media types?

### ISSUE THREAD

**Issue by rykorp** [appdotnet/api-spec#11]
Looking over the API doc, could images be generalized as a media type which are then subcategorized based on MIME types? this would leave the door open for videos as well. If annotations could be attached to the media type, then we could create a pretty versatile bucket for dumping metadata (like EXIF). This could keep the core objects pretty small.

**Comment by DanFarfan** [comment]
I'm new here. I don't see a way to "vote up" honging's comment.
I agree completely. Came here to open the same issue.

**Comment by berg** [comment]
I'm not quite sure I fully understand, so could you help me understand how this might be different than an attachment annotation that would allow you to include metadata?

**Comment by rykorp** [comment]
Referencing https://github.com/appdotnet/api-spec/blob/master/objects.md makes note of an "image" type (or is an image simply a subset of an attachment type? this doesn't seem to be clarified in the spec). 

Instead of having an image: 
{
    "height": 512,
    "width": 512,
    "url": "https://example.com/image.jpg"
}

Once could generalize it further by not assuming the attachment is an image, but a generalized media type: 

{
    "mimetype": "image/x-png",
    "height": 512,
    "width": 512,
    "url": "https://example.com/image.jpg"
}

Which would let you embed videos as well: 
{
    "height": 512,
    "width": 512,
    "duration": 60, 
    "mimetype": "video/mp4",
    "url": "https://example.com/video.mp4"
}

or who knows? 
{
    "mimetype": "image/svg+xml",
    "url": "https://example.com/maybe-svg-will-take-off-one-day.svg"
}

Expanding on this, an image might look like: 

{
    "height": 512,
    "width": 512,
    "mimetype": "image/x-jpg",
    "url": "https://example.com/image.jpg".
    "annotations": {
        "exif:ImageWidth": 512
    }
}

**Comment by berg** [comment]
Image is specifically for user icon and cover image. It's not the full and proper image annotation that we'll be adding (working on a draft of that as we speak.), more of a standard user schema for being able to have clients render posts from a user.

**Comment by jschlesser** [comment]
It would be nice to have resolution info and maybe size (kb) info in the image objects as well.   This might complicate media vs simple image but I think it will be necessary given screen and connectivity diversity.

**Comment by orianmarx** [comment]
We're using an oembed annotation for this purpose: https://github.com/appdotnet/object-metadata/blob/master/annotations/net.app.core.oembed.md
