### ISSUE TITLE
Should be able to write a post in JSON

### ISSUE THREAD

**Issue by beccadax** [appdotnet/api-spec#110]
Currently, all communication between client and server is in JSON, except for the post-creation interface, which uses form data encoding, but with embedded JSON for some of the structured data. It'd be nice if we could instead send the post in JSON (with an appropriate Content-Type header, of course); I know this would remove a large, rather questionable piece of code from my AppNetKit.

**Comment by abraham** [comment]
Ran into this issue using backbone.js. I ended up having to post directly with jQuery instead so this addition would be awesome.

**Comment by mthurman** [comment]
This has been fixed. We still aren't supporting things besides `text` and `reply_to` yet, but we will be soon.
https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#create-a-post
