### ISSUE TITLE
Maximum Post Size

### ISSUE THREAD

**Issue by abitgone** [appdotnet/api-spec#113]
Alpha supports 256-character messages, but is this a hard-limit for the App.net platform, or is there no arbitrary limit?

Additionally, what is the maximum post size, in KB, that is supported via the API. The discussions going on over on issue #79 talk of embedding photos in the posts themselves – I'm just wondering if this would actually be possible.

**Comment by orianmarx** [comment]
256 characters is the hard limit for the text field of Posts and Messages. Annotations can be added to these objects and can be up to 8192 bytes max. They should not be used for embedding media directly but should instead link out to it.
