### ISSUE TITLE
Image resizing does not work

### ISSUE THREAD

**Issue by yeahphil** [appdotnet/api-spec#115]
The api spec says this about images:

> Images may be dynamically resized on the server by adding w and/or h parameters to the query string of the URL as desired. If one of the parameters is omitted, the omitted dimension will be scaled according to the aspect ratio of the original image. Images will be returned with HTTPS URLs, but can be fetched over HTTP if desired.

However, w and h parameters are ignored if present. Since quite large cover images are allowed, this can cause problems (especially for mobile apps or other bandwidth-constrained clients) when retrieving cover images. It's a less pressing issue for avatar images, but would also be more efficient there.

While dynamic resizing would be great, as a quick minimal solution offering 4 sizes of cover image would let developers get a size pretty close to their needs, and should have less impact on CDN hit rate, processing time needed, etc. For cover images, consider providing:
- w=960 (should be default)
- w=320
- w=640
- original size (don't have this be default)

**Comment by kosso** [comment]
This has been added last night and therefore, fixed.
