### ISSUE TITLE
additional field for client_created_at timestamp

### ISSUE THREAD

**Issue by tonymillion** [appdotnet/api-spec#119]
I realise this could be "cheated" but it would be a "nice to have" addition to the API. It would be up to the client to decide if it trusts it over the server defined created_at flag.

Reasoning: I'd like to have a post queue in my app where you can post with no signal once signal is found it will start the post queue and submit posts to the api. Currently those posts would be tagged with the servers created_at date, even if several hours have passed since the user made those posts.

As I stated it would be up to the client to decide to show the "official" created_at timestamp or the apps client_created_at timestamp. Either way posts would be sorted by id.

**Comment by mthurman** [comment]
I don't foresee this being a part of the core API--one created_at timestamp should be good enough. If this really is an issue for some clients, I think annotations are the solution for this kind of metadata.

**Comment by koneude** [comment]
I would also like to see this kind of annotation on the posts;  I would quite like to have the option to see when a post was written (local to the author). Once this information is also provided by the client app, I can see whether, for instance, the author wrote their post in the middle of the night and then went to bed aftwards, so I don't have to expect a reply within the next ten hours or so. Also, it's much more likely that people who travel keep their devices set to displaying their local time, whereas they'll probably not update their timezone information in the app.net profile ever so often.

**Comment by mattflaschen** [comment]
Here's a draft for a core annotation:

``` javascript
{
    "type": "net.app.core.client_created_at",
    "value": "2013-07-16T19:20:30+01:00"
}
```

It's ISO 8601 (same currently used for UTC), but with a time zone designator.

**Comment by ghost** [comment]
+1

Harold
http://hxf148.com
