### ISSUE TITLE
What would be the best way to implement Push Notification for @mentions

### ISSUE THREAD

**Issue by ralfr** [appdotnet/api-spec#121]
@berg: We are close to implementing Apple Push Notification Services for our iOS Client #AppApp. Obviously, this means we somehow have to constantly query whether users have been mentioned, even when they're offline.

This would go against their rate limit as we will have to use their auth tokens.

Are there any plans to e.g. allow to set up an endpoint on the developers side and ask App.net to notify on mentions?

**Comment by mthurman** [comment]
Eventually, this will be the right way to do push notifications: https://github.com/appdotnet/api-spec/blob/master/resources/subscriptions.md

Subscriptions aren't implemented yet so querying either a user feed or the global feed is the best way to do push right now. If you hit rate limits, let me know and we can work some things out.

**Comment by ralfr** [comment]
Thanks, seems absolutely reasonable. Any plan as to when this might be available, or whether team #AppApp could get early access? We are almost ready with our side of the service but currently go for polling. Every minute...

**Comment by tigerbears** [comment]
Thanks for the notes on subscriptions, Mark. It will be exciting to welcome their arrival!

On a general note: Given that the ADN API is still in alpha, early access to new endpoints for any particular group of third-party developers would be distasteful. Were the API already in production, perhaps there are scenarios in which that would be appropriate, but at least for right now all developers are in the same boat together and have been treated equally. It's the spirit of app.net and should continue to be.

Disclosure: I'm developing an iOS app for ADN as well. I'm not on the verge of implementing push but will be investigating it as the subscriptions endpoints come to life and expect to do so as soon as is reasonably feasible.

**Comment by ralfr** [comment]
@tigerbears Absolutely agree. Didn't mean to create silos here. Just wondered whether subscriptions might already be available but maybe just not documented well enough or something.

**Comment by tonymillion** [comment]
To implement push notifications currently with polling, you'd need to set up a DB with something like <userid> <usertoken> <lasthighestpostid> <device IDs> and use a cron job to specifically poll using the users token, this is fine for now as we have an artificial limit of 100 users thanks to Apple.

This will not scale up at all.

**Comment by kosso** [comment]
Agree on this 100% 

If I find out that a 'team' was given early access to anything, I'll burn the place down.

**Comment by tonymillion** [comment]
Yep I concur with @kosso I'll bring the gasoline, you bring the matches.

**Comment by kosso** [comment]
Naturally, I'm joking ;) 

But but to the topic: as Marks says : Subscriptions are/will be the best thing for this. 

I've had testers ask about Push notifications (which I can do - my Mobods app has them) but polling the streams with a since_id is easy, but not practical, at scale.

**Comment by mthurman** [comment]
We still don't have the subscriptions API up, but since the original question is resolved, I'm going to close this issue.
