### ISSUE TITLE
Seeing/hiding replies from people to people the user does not follow..

### ISSUE THREAD

**Issue by kosso** [appdotnet/api-spec#124]
.. needs to be an option provided by the API and developers.

I see today that ADN has implemented the way that Twitter changed things a while ago. (ie: You no longer see @replies from people you do follow directed at people you don't.)

This made some people happy. This made some people mad.  It's easy to see both sides here.

For me, as it did with Twitter, it removed the serendipitous connections between myself and other people followed by my friends. Now I don't see my friends talking to these people who I might be more predisposed to wanting to follow too. 

In my opinion, this feature needs to be optional. If it's implemented on the 'Alpha' cut of the API, then that's fine. But this needs to be an optional parameter for devs to add to their apps. 

It's a little bit like the 'include_replies' param. But needs to be something like 'include_all_replies'  or something similar.

K

**Comment by texburgher** [comment]
Seconded.

**Comment by matthewp** [comment]
Agreed.

**Comment by loonytoon** [comment]
agreed

**Comment by cmcgovern** [comment]
It's one of those features that's massively more useful in the early days when you're trying to create a network of interesting people but less so when your stream is already fairly busy (not that finding interesting new people is ever a bad thing.)

I'd like to think that "having your stream your way" would be a guiding principle of any service you pay for and in that sense, allowing this to be configurable seems to be a perfect compromise that fits that principle...

**Comment by kosso** [comment]
The way I see it is :
- 'My stream' = Posts by my friends.
- 'Global' = Posts by everyone.  

So what we need is a new stream/endpoint/query :   
- 'My Network' = Posts by my friends, including to those to their friends. 

That could work.

**Comment by ghost** [comment]
That sounds like a good idea. I think hiding those mentions to users that you don't follow should be implemented client-side. The API itself should reflect the stream with all the posts of those I follow.

**Comment by texburgher** [comment]
Yes. (emphasis mine)

**Comment by cmcgovern** [comment]
Why not make it part of the filter API? Then a user doesn't have to configure every client they use...

**Comment by JoshBlake** [comment]
No. Through the filters API, clients should be able to request a filtered view of streams so as to reduce network traffic and processing required on clients, such as mobile devices. There is a trade-off of course, and if a client is doing something that is really an edge case or wacky where it is not possible in the filters API, then of course the client can do that client-side, but the common cases such as this issue's topic and filtering on hashtags, certain people, or annotations should be in the Filter API.

**Comment by ghost** [comment]
As part of the filter API, this is of course useful. And as Josh has pointed out, it will heavily reduce network traffic; depending on the user, of course. But the personalized stream should still contain all posts from those you follow.

**Comment by mthurman** [comment]
This is now a setting in alpha (https://alpha.app.net/alpha-settings/) and in the api (see `include_directed_posts` https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#general-parameters). Please note that this setting is not shared among clients; eventually it may be a part of `app_data`.

Please note, the default for 'My Stream' is to exclude these posts.
