### ISSUE TITLE
API License Not Specified

### ISSUE THREAD

**Issue by webmink** [appdotnet/api-spec#125]
I can't find details of the licensing terms for this API - are they specified anywhere? If they haven't been specified, they need to be; I suggest using the agreement created by http://www.openwebfoundation.org/

**Comment by mthurman** [comment]
Let's move these kinds of issues to https://github.com/appdotnet/terms-of-service. Since this is a general issue, I'm not going to move it. Instead, feel free to open specific issues at the ToS repo.

**Comment by webmink** [comment]
I disagree; the absence of any indication of licensing terms in the API documentation is not a ToU issue, it is a straightforward licensing issue specific to this component that makes it defective. 

Without any indication of the terms under which the API is licensed, it is extremely unsafe to implement it as by default all rights are reserved to its creator and anyone implementing it faces the prospect of a lawsuit in the future (say, when Oracle buys App.Net).  I urge you to take this issue seriously rather than just dismiss it out of hand like this.

**Comment by mattflaschen** [comment]
@webmink :

Am I understanding right that you mean a license on the spec itself (ala the [JLS](http://docs.oracle.com/javase/specs/jls/se7/html/jls-0-legal.html))?

If so, I see your point regarding that being different from the TOS for connecting to app.net's implementation.

**Comment by webmink** [comment]
@mattflaschen Yes, precisely. We have seen this movie before and it ended up with a lawsuit. Let's get this baby under an open specification license - with a strong patent covenant included - before we go any further.

**Comment by bayprogrammer** [comment]
@berg Could you or @daltonc clarify the status of the api-spec. Are developers permitted to use and adapt the API spec for independent (re)implementations?

I like ADN, and am a paying subscriber, but I also want the freedom to work on new iterations of it should the canonical version continue to decay (and it is, the payments system is borked if someone who previous used PayPal tries to renew but no longer has a PayPal account, for example).

If the answer is NO, could you at least make that clear somewhere in this repo so myself and others know not to waste their time? If it's YES, could you add a LICENSE or COPYING file with the terms? Thanks in advance!
