### ISSUE TITLE
Post returned by a delete call does not have is_deleted set

### ISSUE THREAD

**Issue by beccadax** [appdotnet/api-spec#126]
When I send a DELETE to /stream/0/posts/[post_id], the JSON I get back does not include an is_deleted key.  Requests sent a moment later do seem to include is_deleted, so it clearly worked; it's just not reflected in the immediate response.

The fact that the post was deleted can presumably be inferred from the 200 response code, but that seems like a road to very messy code that's constantly patching the server's responses with things it "knows" to be true. If the delete request went through, the server should say that the post has been deleted.

**Comment by mthurman** [comment]
Thanks for the bug report! We just rolled out a fix for this.

**Comment by kosso** [comment]
Is every Post object (in any list too) supposed to have is_deleted set?
(true|false)

Or is is only set when is_deleted===true ?

Currently it's returning undefined on lists. Unless it's true.

K

**Comment by mthurman** [comment]
Right now it's being omitted unless true: https://github.com/appdotnet/api-spec/blob/master/objects.md#post-fields

**Comment by kosso** [comment]
got it. that one had me foxed for a bit.  looking for a boolean on a
possibly undefined.

wouldn't it be better to just have the boolean there always?

**Comment by beccadax** [comment]
Yup, my code is now seeing an is_deleted immediately. Thanks!
