### ISSUE TITLE
incorrect language in streams API documentation

### ISSUE THREAD

**Issue by tonymillion** [appdotnet/api-spec#129]
> The Stream contains frames separated by \r\n. Each frame consists of a message prepended by the length of the message and \r\n. For example:
> 
> 9\r\nHELLO\r\n4\r\n\r\n12\r\nWORLD!!!\r\n

Just to confirm \r and \n would be classified as 1 char not two, so surely it would be 5\r\nHELLO\r\n

And since we're dealing with delimited data like that why is the count even necessary at all since an empty line could be just as good of a delimiter

```
HELLO\r\n
\r\n
WORLD\r\n
\r\n
```

**Comment by mthurman** [comment]
Thanks for the feedback! This is still an early proposal for the streaming endpoint so it's definitely subject to evolution (and will probably change somehow).

That being said, we think that although the length isn't technically necessary, it makes parsing much easier when you have to manage your own memory so it will probably stick around. Some libraries will choose to use it and others won't.

Also, '\r\n' would be counted as 2 separate control characters, not 1.

**Comment by tonymillion** [comment]
Ok, it just seems overly superfluous. 

But I wanted to make sure of this: encoded \r is "one byte" so

HELLO\r\n

is 7 not 9?

**Comment by mthurman** [comment]
Yeah that documentation isn't very clear right now

> Each frame consists of a message prepended by the length of the message and \r\n

When I wrote the docs, I included the leading \r\n also ('\r\nHELLO\r\n') which doesn't match the above sentence.

Hopefully next week we can revisit this part of the API and work on some endpoints/develop the final format. But either way, I'll update the docs so they are at least in agreement.

**Comment by kosso** [comment]
Thank goodness someone else said this. I thought I was going mad counting
characters ;)

Any eta-ish on this part of the API?

I'm wondering whether to roll my own push notification system based on
polling for now. (urgh)
thx
K

**Comment by mthurman** [comment]
This has been released and the documentation has been rewritten: http://developers.app.net/docs/resources/stream/
