### ISSUE TITLE
Counts for Post and Counts permission

### ISSUE THREAD

**Issue by DanFarfan** [appdotnet/api-spec#13]
Besides the specific fields you decide to place into Counts for core object(s), consider making annotations (namespace by user name ) to Counts with as permission = "readonly" for apps outside the namespace, but of course "updateable" for the username that "owns" the count. 

Idea being as a app developer, I can create a count that I want other apps to see but not update (by annotating the Counts of the core object) or I can chose to keep that count private to my app if I use an annotation on the core object itself. 

Am I interpreting correctly that developer annotations on core objects will be private to the developer's app (i.e. not seen by other apps outside the namespace)? If not, that's another issue.  public and private annotations. :-) 

@DanFarfan

**Comment by berg** [comment]
My current thought on annotations for posts is that they would carry the same privacy as the post itself. Apps would only be able to post well-known annotations and annotations within their namespace, at least initially. But if an app could see a post, it could see all of that post's annotations.

Same deal with user annotations (which haven't really been mentioned) — these would be for things like storing read pointers, publicly sharing links to other user accounts, etc.

**Comment by DanFarfan** [comment]
Wow. That's not what I was expecting at all. 
Thanks for the clarification! 

Perhaps the difference in our approaches could best be labeled "life cycle." You seem to be adopting the approach that there really is no life cycle for a post once it leaves the sending client. It's frozen as read only (in biology, something unchanging is dead). Thus the job of your social service is one of distribution at that point. 

In contrast, I would argue that the act of sending a post (or any artifact) into the service from a client is the _birth_ of the artifact, not the death of it. There is no simpler or straight-forward use case I could hold up than "RS counts."  Posts have no counts, so ReSends can't be counted, because posts can't change after being sent into the service. It's really a distribution service. Everything about resends is inherently social, including having the count.

I dunno, I could be wrong of course, but I think you're gonna like the frozen/dead approach a lot less as you go deeper down the rabbit hole. But thanks for the feedback! It's important we're all on the same page.

**Comment by berg** [comment]
Thanks for your feedback! Thoughtful debate is important here.

There may be special cases where a very limited subset of values on a post could change. (Reshare counts, in particular, assuming the reshare action is done via the API. Yes, I know this functionality isn't there yet, but we're certainly thinking about it.) But, in general, immutability of post objects reduces a lot of complexity for developers both in consuming posts and storing them, and I ultimately think this is very valuable in terms of developer happiness.

Aside of the reshare count, what do you think are the most important things to be able to change on a post?

**Comment by orianmarx** [comment]
As the service has currently evolved, we are treating posts as immutable objects and annotations can only be set once the post is created. For keeping track of additional data you might consider providing your own database / service which you could reference in a post annotation.
