### ISSUE TITLE
Feature: adding "post_reply_to_ids" to Filter

### ISSUE THREAD

**Issue by nerolapis** [appdotnet/api-spec#135]
It would be very nice to have "post_reply_to_ids" in the Filter object fields.
- **Type**: A list of Post IDs
- **Description**: returns all the posts that (not*) have a "reply_to" in the the given list of Post IDs (* if "type": "block")
- **Usage**: When I'm watching the "General" flow it would be nice to see (in the Apps) if a given post generated a discussion. Developers can deduce it by the "num_replies" of the Post. After that I would like to see the list of that replies; it seems that at the moment I can only guess asking the OP in "mention_user_ids" Filter list, or looking in more recent posts to see if they are replies to the original.

Thank you all!

**Comment by mthurman** [comment]
The Filter syntax has changed drastically since this was opened. This can now be accomplished with the `one_of` operator and giving a list for `value` in the clause: http://developers.app.net/docs/resources/filter/#filter-clauses
