### ISSUE TITLE
secure/private subscriptions

### ISSUE THREAD

**Issue by dch** [appdotnet/api-spec#138]
I see a use case for businesses that want to support a microblogging API for, say, service interruptions, or notifications, that are secure & private:

This would entail a few changes:
- subscription request would return a [202](http://httpstatus.es/202)
- an event would generated to allow the external API to accept or reject the subscription
- user should be able to unsubscribe again, following same actions as above
- the messages would not be visible to non-subscribers

Thoughts?

**Comment by mattflaschen** [comment]
By subscription, you mean following, right?

**Comment by dch** [comment]
Yup, in principle you can use the same API, but in practice I think it's useful to differentiate between open and closed accounts.

**Comment by orianmarx** [comment]
I'm closing this thread as I think much of this scenario can now be accomplished using the Messaging API http://developers.app.net/docs/basics/messaging/
