### ISSUE TITLE
Should message metadata be outbound data?

### ISSUE THREAD

**Issue by danthorpe** [appdotnet/api-spec#14]
Everyone knows that Twitter launched on SMS with its 160 character limit, which they embraced to restrict content to 140 characters. It also meant that all metadata must be sent inbound with the message data which I think has been a restriction.

Would it be possible to send metadata separately from the message? So, they would be listed in the post's entities, and not contributing to the 140 (or other) character limit? The obvious types of metadata would be URLs, and trailing hashtags (tags not in the message body, but appended to the message at the end).

So, it looks like you've done half of this in your Post object example, the trailing hashtag is listed as an entity, but it's still in the message.

The benefits of this would be that clients can be much more flexible about how metadata is displayed. User's get the full 140 characters for their message content. It would allow for much greater flexibility in how Posts are used - it would be possible to tweet a whole photo album for example.

**Comment by berg** [comment]
I think the post creation user experience is considerably better when including tags and mentions inline. For URLs, we allow the anchor text to be different than the link itself. We will have a character limit, but it'll be higher than 140 characters — we don't care about limiting messages to fit within one SMS. And the URL length won't count against the character limit (but the anchor text will.)

If a client _really_ wants to strip out trailing hashtags, for example, it can. But I'm not sure we can — or want to — force sers to change convention around using short messages like these.

**Comment by danthorpe** [comment]
Okay, sounds good. I wasn't advocating that the tags should be stripped during creation, just that they should not contribute to the character length. But, it sounds like we're on more or less the same wavelength.
