### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by neave** [appdotnet/api-spec#140]
Currently App.net uses the Twitter tradition of using full URLs as the only way to link to content, and offering no way to stress or emphasise text other than SHOUTING.

We _need_ some sort of mark up, like HTML or [Markdown](http://daringfireball.net/projects/markdown/) (just as GitHub uses).  It would be _much more_ expressive, concise, and useful. I and a few others would love to see a subset of Markdown support added to App.net. Then the end clients can render the bold, italic text and hyperlinks how they see fit.

**Comment by JoshBlake** [comment]
Someone mentioned this in a post or elsewhere, and I suggested that with the Annotation API, client could be free to indicate which sections of a post are bold, italic, etc., and other clients could render appropriately if they support the convention.

**Comment by dquick-freelance** [comment]
As post content is currently 256 plaintext characters, I don't see where this requires API support - it would be trivial to implement client-side, with the added benefit that forcing Markdown annotations to use some of those characters might make people think more about what actually needs to be bold, italicized, etc.

**Comment by neave** [comment]
@dquick-freelance You are correct, this probably isn't a spec issue but more of alpha.app.net client feature request. However, if each app.net post includes meta data, it would be preferable to have hyperlinks included in that meta data. That way long URLs and Markdown hyperlinks wouldn't take up valuable text space, and we won't have to resort to URL shorteners.

For example, this:

Here is a [link](https://www.google.co.uk/#hl=en&output=search&sclient=psy-ab&q=test&oq=test&gs_l=hp.3..0l4.809.1057.0.1278.4.4.0.0.0.0.109.332.2j2.4.0...0.0...1c.rBkE7OIrzGE&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.&fp=6dd2acfce60f574c&biw=1680&bih=929)

is better than this:

Here is a link: https://www.google.co.uk/#hl=en&output=search&sclient=psy-ab&q=test&oq=test&gs_l=hp.3..0l4.809.1057.0.1278.4.4.0.0.0.0.109.332.2j2.4.0...0.0...1c.rBkE7OIrzGE&pbx=1&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.&fp=6dd2acfce60f574c&biw=1680&bih=929

**Comment by dquick-freelance** [comment]
The URL linking behavior you describe is already in the API spec under post.entities.links but is not yet complete.

**Comment by neave** [comment]
@dquick-freelance OK, great. I guess I'll champion Markdown support over at alpha.app.net, rather than as a spec addition.

**Comment by mthurman** [comment]
Sounds like this can be closed.
