### ISSUE TITLE
Total number of mentions since a given since_id

### ISSUE THREAD

**Issue by tonymillion** [appdotnet/api-spec#143]
It could be incredibly handy if there was an API method that returned the total count (just a number) of mentions since a given since_id.

E.g.

```
https://alpha-api.app.net/stream/0/users/[user_id]/mentions/count
```

would return the TOTAL number of mentions

```
https://alpha-api.app.net/stream/0/users/[user_id]/mentions/count?since_id=100000
```

would return the number of mentions since post_id 100000

the format of the result would be something like

```
{
   data:{
       count: 47
   }
   meta:{
        ...
   }
}
```

This way developers could display a badge showing the number of outstanding mentions a user has, without "heavily" hitting the API to get all the posts (which of course would be limited to a max of 200 anyway, unless multiple requests were made)

**Comment by tigerbears** [comment]
Seconded. This would come in really handy.

**Comment by kosso** [comment]
+1

**Comment by terhechte** [comment]
Yes, absolutely. I second that.

**Comment by paulyhedral** [comment]
+1

**Comment by fwanicka** [comment]
+1

**Comment by scruffyfox** [comment]
holy god this would be amazing + 1

**Comment by scruffyfox** [comment]
One note, wouldn't it make sense to have the count field in the meta rather than the main object body?

**Comment by tonymillion** [comment]
well it should be in the data, since its technically what you're asking for, not "additional stuff you might need"

**Comment by scruffyfox** [comment]
Ah I see, I miss-read the end point.

Would be useful to have a count in the meta for stream endpoints that way you wouldn't need to do 2 separate requests
