### ISSUE TITLE
api support for sort criteria

### ISSUE THREAD

**Issue by rjo** [appdotnet/api-spec#144]
I'm building a profile view in #Mention that displays a list of all followers.  I'd like to implement an alphabetic partition in my UI (A-D E-J ...) to make this easier to navigate but I would need API support to do it.

If /stream/0/users/[user_id]/following and /stream/0/users/[user_id]/followers supported these additional keys:

<table>
<tr><th>key</th><th>acceptable values</th></tr>
<tr><td>sort_criteria</td><td>username, name</td></tr>
<tr><td>order</td><td>ascending, descending</td></tr>
</table>

and pagination was able to apply to the sorted set, then clients could easily navigate long profile lists in alpha order. This would make it easier for users to casually browse or look for a name in a followers list.

**Comment by orianmarx** [comment]
I agree that this is nice feature to provide in a client. That said, it is very process intensive to do on the backend and given the reality that most follower counts will likely not exceed thousand of followers for quite some time, we suggest you fetch all followers for a user and do the sorting on your end. We're unlikely to add this to the API for a long long time so I'm closing this thread.

**Comment by rjo** [comment]
Fair enough
