### ISSUE TITLE
Provide more information about Mute

### ISSUE THREAD

**Issue by shpakovski** [appdotnet/api-spec#145]
An object [User](https://github.com/appdotnet/api-spec/blob/master/objects.md#user) has a flag `"you_muted": false`. I propose to change it to the date of mute like `"you_muted_at": "2012-08-16T17:23:34Z"`. Then the user would analyze what he said “wrong” or what else happened in the timeline.

**Comment by edent** [comment]
Muting, as I understand it, isn't meant to be seen by the muted party.

You will never be able to tell that I muted you.

A client could, however, record the datetime when the mute button was pressed.
