### ISSUE TITLE
Allow bots to be filtered out of global timeline

### ISSUE THREAD

**Issue by digitalquery** [appdotnet/api-spec#146]
We need a way to mark an account as a 'bot' account so that it doesn't necessarily appear in the main global timeline, mainly to avoid flooding global with posts.

**Comment by JoshBlake** [comment]
Not bot accounts but bot posts. I may authorize an app to do some bot activity that I want done (notifications, passing messages between apps, etc.) and that would be over my account.

**Comment by digitalquery** [comment]
Yes. agreed that marking the "bot" attribute can be applied at the level of a post, but there is a need to be able to mark every post coming from an account as a bot post. As an example, see:
- https://twitter.com/twrbrdg_itself 
- https://twitter.com/testcricket

**Comment by dquick-freelance** [comment]
Bot accounts should be covered by user.type : https://github.com/appdotnet/api-spec/blob/master/objects.md#user-fields

@JoshBlake I can see use for denoting that a post was generated programmatically from an account of user.type != bot - might be best accomplished by an annotation and client convention though, which would also allow us to sub-classify programmatically generated posts at will in some sort of taxonomy. Thoughts?

**Comment by orianmarx** [comment]
Closing this as "bot posts" have been implemented as machine only posts. http://developers.app.net/docs/resources/post/#machine-only-posts
