### ISSUE TITLE
App.net secure (ie: encrypted) messaging standard

### ISSUE THREAD

**Issue by ravisorg** [appdotnet/api-spec#149]
@orian (the [App.net orian](https://alpha.app.net/orian), not the [github orian](https://github.com/orian)) suggested I post this here, so... here it is...? :)

I'm requesting feedback/comments/suggestions from App.net users (and client developers) on the possibility of an App.net secure (ie: encrypted) messaging standard. 

Details and demo at http://priv.im/about

Also see: https://alpha.app.net/ravisorg/post/253828

Note this doesn't (currently) require any changes to the API. I was assuming no changes would be possible so build around the current spec. If there are ways this could be integrated/standardized with the API somehow, that would be cool too.

Thanks!

**Comment by ravisorg** [comment]
Damn, the timing on annotations couldn't have been better. Gotta think of a schema....

**Comment by jdscolam** [comment]
I'm down with this idea, though I need to go through your spec, as long sa it doesn't flood the global stream with useless messages.

**Comment by ravisorg** [comment]
@jdscolam They're not useless, they're encrypted ;)

Actually now that annotations are supported (and 8kb! woot!), we can move the encrypted text to the annotations. So the post.text would simply show "@recipient Private message"

**Comment by ravisorg** [comment]
This is currently what priv.im is using (eg: version 1):

``` json
{
    "type": "im.priv",
    "value": {
        "version": 1,
        "message": "128戍蘯怳蠅耣軩翐捆譾噰纛瘒烹...",
        "session_keys": [
            {
                "recipient": "username1",
                "key": "128戍蘯怳蠅耣軩翐捆譾噰纛瘒烹..."
            },
            {
                "recipient":"username2",
                "key":"128戍蘯怳蠅耣軩翐捆譾噰纛瘒烹..."
            }
        ],
        "signature": "128戍蘯怳蠅耣軩翐捆譾噰纛瘒烹..."
    }
}
```

Does anyone think this should be included in net.app.core.X? I'm not so sure... Should private messaging be a standard thing or a third party spec?

UPDATED: to show the current format for version 1. Version 2 is being worked on and will be better, most notably that you'll be able to store annotations, etc in the encrypted data. ie: you can encrypt more than just the text.

**Comment by jdscolam** [comment]
Yeah, though I can see there being TONS of Private messages, so Global
would have to filter.

----- Original message -----

**Comment by mattflaschen** [comment]
Encrypted messages should be visible only to their recipients (pending issue #33).  That resolves the global feed issue and makes logical sense.

**Comment by DaveWoodCom** [comment]
Should there be a flag on all posts that specify whether or not to include the post in the global stream? I'm thinking about encrypted messages, but also any machine only readable post. Some apps will build on top of app.net in a way that the post will be jibberish for humans. Apps we haven't thought of yet, and they should have a way to hide their posts from anyone not specifically looking for them or else the global stream may become useless. Eg. a chess game sending moves across app.net.

**Comment by ravisorg** [comment]
@mattflaschen hot damn, that level of access control would be amazing on so many levels, but definitely would apply here as well.

**Comment by ravisorg** [comment]
@DaveWoodCom Yes, that's been the concept of App.net from the beginning (I believe). They'll be lots of "non twitter status update" type messages flying around, and they'll be lots of ways to filter them. That's a different problem from this, but this could definitely make use of it.

**Comment by DaveWoodCom** [comment]
@Ravisorg Right, that is the plan for app.net, which is why it seems strange that this flag is not already in the spec. Unless it is already and I've just missed it. I think posts should have to opt in to the global stream, verses opt out. You don't want users to have to filter out noise, or they'll have to set up new filters for every new app that uses the stream. 

I just mentioned it in this tread since it would apply here also. 

On the encryption front, a standard would benefit everyone I think. We could store the users public key in the app_data dictionary of the user object. A well known location that enables all apps to encrypt messages for any user, so you don't have to know what client the recipient uses.

**Comment by ravisorg** [comment]
Ok, I'm going to flip into ultra paranoid crazy apocalypse survivor mode here for a moment, which is fun, but not healthy long term. Like an ice cream and chocolate diet...

For a cloud based private key store we have (as I see it) two main problems:
1) A remote attack, where the attacker can make network requests but doesn't have physical access to the server
2) A local attack, where the attacker had direct access to the data on the hard drive

# The setup

We have a remote server that anonymously holds private keys. Each key is indexed by a hash, ideally the user's email address + private key password, but since we don't see the contents of the hash we can't enforce this. For the user's own safety (avoiding collisions with other users) it would make sense for clients to use something unique to the user (like an email) combined with something no one else knows (like a password). And it needs to be somewhat standard so different clients can still retrieve the key.

So the server itself has no knowledge of who owns what key, but it still knows that it has a collection of X keys, and that's dangerous, because even if everyone in the world had a key stored on the server, that's FAR fewer attempts needed than if we're searching the entire possible keyspace.

# Problem 1, remote attackers

If we can assume the hash is always email+password, a remote attacker can just keep trying hashes of email+random until he stops getting a 404. Bingo, key found.

~~Possible solution 1: What if the server returned a result on every request? Since it's encrypted, there'd be no way to tell if it was valid or not without trying it.~~ Problem: If I create a hash of "myemail@gmail.com" + "password" and get back a result, I can try to decrypt it with "password" and see if it looks like a valid key pair. If it doesn't, then the server sent me garbage and I try again. This is really no different from a 404.

The easy (if less fun) way is for the server to delay sending back a response by (say) 5-10 (even 30) seconds and deny multiple connections from the same IP at once, on top of throttling bad requests from a single IP. This wouldn't affect a legitimate client too much, because it would be very rare to retrieve a private key from the server, it would only happen when you started using a new client / reinstalled your laptop / etc. But a 5-10 second delay would kill any remote brute force methods for all but the very weakest passwords. Even if you had a very large botnet making attempts you'd run out of tries pretty quick.

# Problem 2, local attackers

There's really no solution at all to this one, except to keep people from getting access to the filesystem. That's not a big problem for the general public (a decent ssh key, a firewall, and up to date patches will keep the vast majority of people out) but I'm assuming here that the local attackers are your friendly local government serving a subpoena to the person hosting the server, in which case they walk right by any security features in place.

Possible solution: TOR. A hidden tor server would be (in theory) impossible to trace to the origin. Clients could connect, request their key, wait 5-10 seconds, and retrieve it without anyone knowing where the actual server is. This would be moot if someone somewhere knew where the real server was located, they could simply be served with the subpoena and the TOR service is revealed. (downside, compatible App.net clients would have to have a TOR client build in)

This could be bypassed by loading up a throwaway credit card with enough donations to last a reasonable number of years, build a script that creates an AWS account, sets everything up automatically without you ever seeing account usernames / passwords / IP addresses, and then destroy the card / any info regarding the server. So long as the person didn't have a photographic memory the little information they did know would be gone pretty quickly. The server could easily spawn new instances of itself and destroy the old ones every now and then to keep things fresh (perhaps even a pair or trio of servers so if one goes down the other can re-generate a new twin).

If you wanted to get really fancy you could set it up so people could donate bitcoins to the account to keep it running indefinitely. The server would convert the coins every month and refill it's rechargeable disposable credit card account.

There would have to be a lot of redundancy (Mars Curiosity level redundancy) because there would be no way to get into the server to fix things if they went wrong, and if they did, boom, everyone's private keys are gone. Fun to think about, probably not realistic.

So you'd have to have someone, somewhere, with access to the server to maintain it. But no one could know who that person was. So then it comes down to trust, and this is were paranoia goes nutty. Would you trust this kind of service, not knowing who had set it up? What if I'm a government agent sent to collect everyone's keys? :p

On the other hand people who were that paranoid would activate the "paranoid mode" in their client and keep their keys locally. So perhaps we don't have to worry about that. For the vast majority of people everything would just work and would be reasonably secure...

...still thinking, these are just initial ideas...

(of course this would work for any keys, not necessarily just App.net keys, so while it might not be worth all the trouble for a simple encrypted message format on App.net, as a global key store it might be more interesting)

**Comment by ravisorg** [comment]
Possible abuses:

Since its completely anonymous and the data is encrypted (so we cant inspect it) people could start using it for free online backup. We could greatly discourage this by limiting each key it a few kb (whatever is necessary for a large key) and again delaying save requests like we delay retrieve requests. This would make it the slowest and least responsive backup system ever. People could still save shards of text files and such, but you wouldn't be able to share the URL, because then anyone could delete it... Possibly solved?

**Comment by ravisorg** [comment]
A much more complex, but much better system: http://www.cl.cam.ac.uk/~jra40/publications/2010-SPW-key-storage.pdf

**Comment by jdscolam** [comment]
That's deeply fascinating to me @ravisorg.  I need to chew on it more, but I like where you're going.

**Comment by ravisorg** [comment]
Thinking about splitting the encrypted data up (interpolating it) among multiple servers, each in different countries run by admins in different jurisdictions. Might solve the subpoena problem, and also some of the trust issue. Even if several of the servers were run by evil admins or compromised in some way, you'd need access to data on all of them in order to reconstruct a key. And even then you'd have no idea how the files fit back together without figuring out the hash (in which case you wouldn't need to compromise the server, you could just request the files directly)...

The biggest downside is there are now multiple servers to maintain by multiple people. If one server goes away everyone loses their keys. There would have to be clones run by even more people...

**Comment by orianmarx** [comment]
@ravisorg I'm closing this issue. If you'd like it to remain active, please open a new issue on https://github.com/appdotnet/object-metadata and include a reference to appdotnet/api-spec#149 to link back to this discussion.
