### ISSUE TITLE
How is this different from http://activitystrea.ms ?

### ISSUE THREAD

**Issue by darrelmiller** [appdotnet/api-spec#15]

**Comment by simondlr** [comment]
Activity Streams is a standard. App.net is intended to be a social service in its own right.

**Comment by berg** [comment]
Naturally, we spent time looking at activitystrea.ms. Given that avoiding XML was an important goal to me, the relatively sparse number of implementations of the JSON version thus far (and those implementations veering far away from the standard), the lack of widespread client support, and so on... the cost of the impedance mismatch between the service we wanted to build and what the standard outlined seemed to outweigh the benefit of compliance with that standard.

If you have a use case I haven't considered, I'd be happy to hear it, but I'm going to close this issue for now.

**Comment by sriks6711** [comment]
Here's a case. IMHO, the world does not need another API specification for the kind of service being envisioned to be built when still-evolving and open and extensible standards like ActivityStreams might very much suffice to build real-time feed service such as the one being attempted here and then some.

While it is an apples to oranges comparision, we mimicked core, if not all, Twitter, err, microblog social network, functionality (users, posts, followers, media) with ActivityStreams in 2 weeks with 3rd year UG summer interns inspite of the low-hanging fruit of just forking Identi.ca source code. Am sure what is being done here is very complex but I would like to see a debate on what exactly is being planned to be delivered that ActivityStreams does not meet?

I particularly would like the makers not to reflect their personal biases (as evidenced by using phrases like "avoiding XML was an important goal to me") in a service which as I understand is for a public good. Sure, avoid XML but not with prejudice nor being outright dismissive of what is still relevant and one of the building blocks of the semantic web. Sorry to digress.

**Comment by matthewp** [comment]
As a user I would also find the service more useful if it was based on open standards rather than a new API that overlaps 90% with others.

**Comment by ches** [comment]
Concur with much of what @sriks6711 said. OStatus also has a lot of merit in the federation discussion (#22), and ActivityStreams is part of the OStatus suite.

**Comment by alexgoesunder** [comment]
I totally agree with @sriks6711. App.net must be based on an open standard. OStatus, ActivityStreams, tent.io etc. it doesn't matter much. Community discusses and makes protocol-related decisions, App.net implements the protocol and makes a fast twitter-alike service on top of it.

**Comment by mattflaschen** [comment]
On August 10, [Dalton committed](http://daltoncaldwell.com/a-response-to-brennan-novak) to supporting "Activitystrea.ms Atom & JSON feeds".
