### ISSUE TITLE
Notification of deleted posts

### ISSUE THREAD

**Issue by nanek** [appdotnet/api-spec#156]
I currently index the global stream to provide the search at http://appnet.herokuapp.com/search
I need a way to determine which posts have been deleted, so that I can remove them from the index.

Is there an existing API endpoint that I can poll to get a list of the deleted post ids? If not, can some sort of API, RSS feed, or notification mechanism be implemented so that I, and presumably other similar services, can handle deleted posts properly?

**Comment by coyled** [comment]
I asked something similar in #32 ; no response yet.  Right now the only way to get deleted posts is to fetch each post and see if is_deleted==true , which is what I'm doing for http://search.256.is

**Comment by nanek** [comment]
I'm moved my comment to Issue #32 so I'm closing this ticket as a duplicate of that issue.
