### ISSUE TITLE
News Release Annotation

### ISSUE THREAD

**Issue by swhitley** [appdotnet/api-spec#157]
I'd like to propose implementing the news release format as an annotation.  The specification was originally created as a microformat:   http://smr.iabc.com/wp-wiki/Main/XHTMLhRelease08

This specification uses other schemas, so I'm not sure if it is possible to represent parent-child relationships.  That's an interesting challenge.
# annotations

**Comment by orianmarx** [comment]
@swhitley I'm closing this issue. If you'd like it to remain active, please open a new issue on https://github.com/appdotnet/object-metadata and include a reference to appdotnet/api-spec#157 to link back to this discussion.
