### ISSUE TITLE
Streams by annotation type

### ISSUE THREAD

**Issue by ghost** [appdotnet/api-spec#159]
When Streams is launched, I'd like to see it include the ability to fetch a stream by annotation type. I can see this being tremendously useful for something like a music discovery or Instagram-like app. While this could be done with app streams, it would be more useful if such streams were app agnostic.

**Comment by sull** [comment]
great suggestion.

**Comment by orianmarx** [comment]
Closing this as this has been rolled out in our Streaming API http://developers.app.net/docs/resources/stream/
