### ISSUE TITLE
Suggestion: Use microdata instead of classes in html

### ISSUE THREAD

**Issue by matthewp** [appdotnet/api-spec#16]
The Post object includes an html property which, in this example, includes classes.  Since the className could potentially conflict with the client's own css, I would recommend replacing it with microdata. So the example becomes:

``` html
<span itemprop=\"mention\" data-mention-name=\"berg\" data-mention-id=\"2\">@berg</span> FIRST post on <a href=\"https://join.app.net\" rel=\"nofollow\">this new site</a> <span itemprop=\"hashtag\" data-hashtag-name=\"newsocialnetwork\">#newsocialnetwork</span>.
```

**Comment by berg** [comment]
Great idea, thanks!
