### ISSUE TITLE
Total number of mentions

### ISSUE THREAD

**Issue by meap** [appdotnet/api-spec#160]
It would be very useful to have total number of mentions in the user's profile. Same like currently we have for followers, following, posts.

``` json
"counts": {
    "follows": 100,
    "followed_by": 200,
    "posts": 24

    "mentions": 354
},
```

**Comment by kosso** [comment]
Not a fan of this approach / idea. 

What would be more useful is to have the ability to just return a count from any of the Post/User API endpoints, rather than returning all the data. 

Maybe, since the arrival of the meta response envelope, that might be easier now.

**Comment by duerig** [comment]
This would be useful if bulk-lookup of users is cheaper than bulk-lookup of mentions endpoints.
