### ISSUE TITLE
Well-Known Annotation Namespace for Additional Social Actions

### ISSUE THREAD

**Issue by sull** [appdotnet/api-spec#161]
Beyond the social actions defined in the API, we should discuss what the right namespace would be for additional actions that can be defined via the Annotations API. 

It does not appear that app.net intends on focusing on this initially as per the list from doc:
- Geographic data
- Media enclosures, e.g., photos, video, etc.
- Long-form content
- Attribution and source
- Additional content license grants, where users can opt in to Creative Commons licensing, etc., if desired.

I suppose prior to making suggestions, it would be best to know if their is room for native well-knowns to handle social actions such as:
- Upvote: like, favorite, +1 etc
- Downvote: dislike, hide, mute
- Share: repost, recommend, send to (email, ext. network) 
- Save: bookmark, read later
- Gesture: nod, highfive, handshake etc

Annotations are very exciting but also prone to becoming unwieldily. Getting all of this well-defined sooner than later will be useful to all.

**Comment by beccadax** [comment]
How do you envision these being used? You can't attach an annotation to someone else's post (or indeed, to an existing post at all), so do you see these being attached to your own reply posts somehow?

**Comment by sull** [comment]
Yeah it would be part of a reply or a targeted @mention post. I could make an argument for a diff object to be created for "actions" but need to see where this conversation goes. 

I recall the tough discussion on this type of stuff during Activity Streams spec creation. Some links:

http://wiki.activitystrea.ms/w/page/23655855/Actions

http://wiki.activitystrea.ms/w/page/1359319/Verb%20Mapping

**Comment by jeffgorder** [comment]
I'd second a visit to the Activity Streams spec. Annotating the message with an action or "verb" - finish something, deliver something, delete something - would be of significant value to many applications. This might be even more interesting when coupled with machine flagged messages.

Mass transparency could be enabled if applications, when the context is correct of course, post when an activity has happend annotated with the details of what happend. Having the choice to post an action publicly might be interesting as well.

**Comment by mattflaschen** [comment]
@jeffgorder yes, app.net has [committed](http://daltoncaldwell.com/a-response-to-brennan-novak) to implementing Activity Streams (#18), and it could potentially work well in conjunction with this issue.

**Comment by orianmarx** [comment]
@sull I'm closing this issue. If you'd like it to remain active, please open a new issue on https://github.com/appdotnet/object-metadata and include a reference to appdotnet/api-spec#161 to link back to this discussion.
