### ISSUE TITLE
Move annotations discussion to a separate repo

### ISSUE THREAD

**Issue by tgvashworth** [appdotnet/api-spec#166]
It seems to me that this repo is not the right place for the annotations discussion, because it's difficult to distinguish from API issues and because the resultant annotation spec is not part of the core API.

I propose moving to appdotnet/annotations-spec, where there'd be a README with an intro, and then examples added via pull requests. All annotation issues would be discussed there.

**Comment by sull** [comment]
Makes sense.
+1

**Comment by dquick-freelance** [comment]
Makes a lot of sense - +1

**Comment by jdscolam** [comment]
+1

**Comment by matthewp** [comment]
I disagree, net.app.core annotations are part of the API spec.  We just need to use labels so you can filter.

**Comment by tonymillion** [comment]
It _WOULD_ be fine if there weren't trivial discussions every 15 minutes about CHESS ANNOTATIONS. I also vote for annotations to be moved out of _IMPORTANT_ api-spec discussions.

**Comment by mattflaschen** [comment]
We're discussing chess annotations for the same reason the other ones are being discussed here, for inclusion into net.app.core.

If you're not interested in a particular thread, GitHub lets you mute it.

**Comment by mthurman** [comment]
In general, issues are an api topic and thus I don't think we're going to make a separate repo for that right now. The less administrivia/overhead the better IMO. I'm trying to label things with the "annotations" label and github has pretty good email control so I think the signal-to-noise is still good.
