### ISSUE TITLE
De-authentication?

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/api-spec#168]
How do I go about deauthenticating a user? As soon as I present them the login page again, it automatically re-auths and doesnt give the user a chance to re-enter their details.

I've tried adding a no-cache token on the url ("cache=currentTimeMillis()") but no luck

**Comment by swhitley** [comment]
Good question.

**Comment by berg** [comment]
You can send them to `/oauth/authorize` instead of `/oauth/authenticate`, if you like, which will force a user to hit "Accept" again. This behavior is by design, because it makes low-friction login buttons easy.

**Comment by beccadax** [comment]
What if you want to let the user log in with a different account? Even `/oauth/authorize` doesn't present an obvious UI for choosing a different account (at least not on an iPhone).

**Comment by romainpiel** [comment]
"Deauthentication" should be done by clearing system's cookies (see https://alpha.app.net/kosso/post/469440)

**Comment by berg** [comment]
Or send them to:

`https://alpha.app.net/logout/`

Or use the password flow:

https://github.com/appdotnet/api-spec/blob/master/password_auth.md
