### ISSUE TITLE
Discovery of documentation of annotation formats

### ISSUE THREAD

**Issue by fields** [appdotnet/api-spec#170]
It would be nice if there was a way included with annotations to get more information about the expected format of the annotations themselves.

Ideally, there would be some sort of standardization of format for how to describe them, but that's a lot of formalization this early. In the short term, I'd like to see a url included which is intended to be a pointer to more information about the annotation format used.

**Comment by beccadax** [comment]
I'm not sure this is worth taking up space in a data structure with rather limited size. Perhaps instead App.net can provide us with a registry where people can register the annotations they're using, along with a description of them. Even a wiki would be helpful for this purpose.

**Comment by mthurman** [comment]
It's pretty bare still, but: https://github.com/appdotnet/api-spec/wiki/Annotations. I agree that it doesn't really belong in the annotation itself. I think community standards are better than technical ones in this case.
