### ISSUE TITLE
Way to do ad-hoc query to get direct replies

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#171]
As now documented, [/replies](https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#retrieve-the-replies-to-a-post) returns the whole thread.  I would like a way to get a list of direct replies to a given post ID.

Among many other things, this will help prevent cheating/disruption in correspondence chess.  If a move is a reply to the prior move, this will make it easier to detect and ignore double moves.

Note, #135 would allow this, but it's requesting a filter, rather than an ad hoc endpoint like /replies.

I also realize I can do it by getting /replies then filtering the unwanted posts, but that consumes time and bandwidth, particularly given the 200 post limit per response.

**Comment by orianmarx** [comment]
This is due to the way our backend is architected. Storing reply trees can become pretty complex so to optimize we store them in a way that requires fetching the whole thread and recreating the reply structure. We're very unlikely to change this approach so I'm closing this thread.
