### ISSUE TITLE
oEmbed in Link Entities

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#172]
May of the links that people post have eEmbed data associated with them.
(http://oembed.com/)

For example, a YouTube page has information about thumbnails, embedable media, etc.
E.g. http://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DD7hkukXrPx0&format=json

Currently, I use a 3rd party service like Embed.ly to get oEmbed information from URLs posted to App.net.

I would like that information returned in an entity from the App.net API.

ie.

```
"links": [{
    "text": "Cool video",
    "url": "http://www.youtube.com/watch?feature=player_embedded&v=D7hkukXrPx0"
    "pos": 20,
    "len": 13
    "oembed": [{
        "thumbnail": "http://www.youtube.com/user/TEDTalentSearch",
        "html": "<iframe width=\"480\" height=\"270\" src=\"http://www.youtube.com/embed/D7hkukXrPx0?fs=1&feature=oembed\" frameborder=\"0\" allowfullscreen></iframe>",
        ***etc***
    }]
}]
```

Or is this something better suited to annotations?

**Comment by edent** [comment]
Well, it's now in annotations - if a client supplies it:
https://github.com/appdotnet/api-spec/blob/master/annotations.md#embedded-media

**Comment by orianmarx** [comment]
This is something we probably won't do for a long, long time if at all so I'm closing the thread. As you've noted, clients can supply this data themselves when making posts.
