### ISSUE TITLE
Syntax Coloring

### ISSUE THREAD

**Issue by 3lvis** [appdotnet/api-spec#174]
Since appdotnet is mostly full of developers and people close to technology and since sharing really smalls snippets of code is a day to day thing that we do, mostly for fun and this are perfect for microposts. I would love to have syntax coloring in appdotnet.

What do you guys think?

``` javascript
if (tooStupid) {
   // remove this issue in your favorite programming language.
}
```

**Comment by mattflaschen** [comment]
This could be done as an annotation, similar to the links:

``` javascript
{
    "type": "net.app.core.programming.embed",
    "value": [
        {
            "language": "Java",
            "pos": 20,
            "len": 13
        },
        {
            "language": "C",
            "pos": 50,
            "len": 23
        }
    ]
}
```

Like the links, you can have more than one.

Posting apps could let the user input in a format that supports language tagging, like Markdown, auto-detect it, or ask the user.

Viewing apps could display as they liked, with the automatic fallback  being normal text.

**Comment by mthurman** [comment]
I don't see this as a core annotation but if you guys would like to develop a community annotation, go for it: https://github.com/appdotnet/api-spec/wiki/Annotations

**Comment by orianmarx** [comment]
@NSElvis @mattflaschen I'm closing this issue. If you'd like it to remain active, please open a new issue on https://github.com/appdotnet/object-metadata and include a reference to appdotnet/api-spec#174 to link back to this discussion.
