### ISSUE TITLE
Better auth page

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/api-spec#175]
There needs to be a better/more responsive authentication page. On devices such as the Wildfire/wildfire s, the page is full size and not optimised (unlike bigger phones such as my galaxy s2)

It would also be awesome if we could inject our own CSS styles to make the page look.. more like part of the app

**Comment by swhitley** [comment]
We have been having issues on Windows Phone as well.  The ADN team has been working on it (@voidfiles), but I'm afraid responsive designs aren't supported perfectly on all devices.  I highly recommend jQuery Mobile.

**Comment by mattflaschen** [comment]
I don't know any OAuth provider that let's the calling site inject CSS like that.  It's supposed to look like Alpha, to reassure users that their information is being shared Alpha -> app in a normal sanctioned way.

**Comment by berg** [comment]
If you want to make your login flow look more like part of the app, I suggest using the Password flow:

https://github.com/appdotnet/api-spec/blob/master/password_auth.md
