### ISSUE TITLE
Allow reply without @ syntax

### ISSUE THREAD

**Issue by graiz** [appdotnet/api-spec#176]
Since a reply in App.Net is a semantically captured it doesn't have to suffer from the weird syntax that was invented on twitter to deal with txt message limitations. 

I hit reply. Then I type my reply. The related message context can be preserved. This could allow different user agents to thread & nest comments without the awkward text syntax.

**Comment by edent** [comment]
That already works.  If you hit "reply" but delete the @ name, the post still gets an "in_reply_to" set.
So your message will show up in the thread.  It will not show up in the user's mentions.

**Comment by mthurman** [comment]
As @edent mentioned, mentions and replies are 2 separate things in App.net. On Alpha, we encourage replies to have the @ syntax so conversation participants can see that there are new posts in the thread easily (through mentions) but it is not an API requirement.
