### ISSUE TITLE
Reconsider API endpoint for starring posts

### ISSUE THREAD

**Issue by jdp** [appdotnet/api-spec#177]
Currenly the way to star a post through the API is to send a POST request with a `post_id` to https://api.app.net/stream/0/posts/[post_id]/star - this seems more RPC style than RESTful style. I think it would be nice to just post to a starred collection resource or something under the /user endpoint.

Example: Sending a POST request to https://api.app.net/stream/0/users/[user_id]/starred with a `post_id` would add that post to the collection of that user's starred posts. Performing a GET request on that same URL would return the collection of that user's starred posts.

**Comment by orianmarx** [comment]
Thanks for the suggestion. Either approach seems valid and we're going to keep things the way they are so I'm closing this thread.
