### ISSUE TITLE
Upgrade to developer account

### ISSUE THREAD

**Issue by philipbjorge** [appdotnet/api-spec#178]
Hi,
I originally purchased a regular account to app.net, but would like to bump it up to a developer's account.
Is there an interface for doing this? Who should I contact to get this handled?

**Comment by lasar** [comment]
I just emailed join@app.net and asked them to do just that.

**Comment by berg** [comment]
You can handle this in the "My Settings" section of Alpha now.

**Comment by philipbjorge** [comment]
Thanks for handling this so quickly!

**Comment by jmergy** [comment]
I did the same thing and played the upgrade through My Settings a couple of days ago. All good.
