### ISSUE TITLE
'text' field in Post objects should be HTML escaped

### ISSUE THREAD

**Issue by jazzychad** [appdotnet/api-spec#179]
Hear me out...

The `text` of a Post object should be HTML escaped (&gt; &lt; &amp; etc...) so that it is easy to display the text in an HTML rendered setting. I realize that there is an `html` version of the text returned, but there is so much noise of inline markup it makes it very difficult to customize the behavior of the entities within.

Right now cross-site scripting bugs can be triggered by rendering posts straight in a browser page.

"So?" you might say... "just escape the HTML yourself before displaying it."

That would be lovely, except if you are using the `entities` hash to replace usernames, hashtags, and links in the text with custom links with custom actions (such as in mobile apps w/ custom url handlers). If you manually replace every <. >, &, etc with their escaped counterpart, the indexes of the entities all become wrong.

"So?" you might say... "just replace the entities first, then replace the <'s and >'s"

That would be lovely, except now I'm nuking all of the angle brackets I just inserted with the entities dictionary.

There are some gross hacks which would involve replacing the entities with other custom escape sequences first, then replace <'s and >'s then replace the custom escape sequences with proper <'s and >'s, but this is getting unwieldy...

So, I propose that the `text` field come pre-html-escaped for the sake of ease and protection of several security problems that will inevitably pop up with the most common way of displaying post text (in a web view).

I know we are all hating on Twitter at the moment, but they have done this since day one in their API, and I think it is the right decision.

Please discuss.

**Comment by swhitley** [comment]
This is definitely worth considering.  If one developer doesn't encode the HTML and an XSS attack occurs, App.net will be blamed.

**Comment by mattflaschen** [comment]
The text property should be just that, text.  &amp;lt; and friends are HTML.  I don't agree that with the HTML version "there is so much noise of inline markup it makes it very difficult to customize the behavior of the entities within."  I found it easy to find the values I needed by searching on data attributes (e.g. data-mention) then injecting links.  If you're having an issue with this, I can help.

A lot of developers will not be using text for HTML rendering.

**Comment by jazzychad** [comment]
@mattflaschen i agree that dealing with the HTML version and finding data-attributes would be easy in a web/js environment when you can use something like jQuery to rip through them, but not all environments have it that easy (e.g. mobile)

**Comment by berg** [comment]
If you need a simple HTML version, use post.html. If you want to do something more complicated, you're on your own to do something smart with text. I think we do a very good job of providing a middle ground. Assuming that these post objects are somehow tied to HTML, and thus need some kind of lowest-common-denominator protection against XSS built in by default, seems like a bad idea.

If you're on a mobile client, don't use HTML. The entities hash is specifically intended for it to be trivial to build an NSAttributedString.
