### ISSUE TITLE
Document more clearly which endpoints can be used unauthenticated

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#181]
The docs aren't clear which endpoints can be used without a token (unauthenticated) and what the rate limits are for that (seems to be low, which makes sense if it's only for casual testing).

One place to put this info would be auth.md.

**Comment by mthurman** [comment]
This is now documented on the "resources" index: https://github.com/appdotnet/api-spec/tree/master/resources.

The unauthenticated endpoints are mostly meant for JSONP applications (widgets, etc). 

I'm going to close this issue and any questions about rate limits can be moved to #185.
