### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by ajmckee** [appdotnet/api-spec#185]
This morning (UTC 10 ish) I hit some rate limits and got issued with a HTTP 429. This I suspect was the correct behaviour as my client went from 1 request per second to 1 every .5 seconds on the global steam URI. 

Reading thought the docs however I was not able to locate any information in relation to rate limits. 

An examination of the headers revealed the following 

```
X-RateLimit-Remaining: 4992
X-RateLimit-Limit: 5000
X-RateLimit-Reset: 2615
```

Most of this is pretty self explanatory however upon subsequent requests, the limits appeared to alternate between the above and a limit of 60.

Secondly its not clear when the reset will occur. Is it in 2615 seconds? 

Perhaps a light note on being a good app.net client and handeling requests would be helpful so we don't all cream things. 

TIA

**Comment by mxml-barmstrong** [comment]
Thank you for the feedback. We do need to document what the rate limit headers mean. In brief: Remaining tells how many calls you have left, Limit tells you how many that is out of (total capacity), and Reset is how long (in seconds) until your Remaining is reset to Limit. Also, the headers only show the most restrictive limit on your call, so for certain endpoints and methods this will change, which describes the different responses you saw.

**Comment by ajmckee** [comment]
Cool, thanks for prompt reply. I presume if I need a higher rate (Doubtful at present) I can request nicely and promise a beer....

**Comment by kosso** [comment]
Just a comment to add that according to appnetstats.com there's only about
10 posts being (currently) made per minute on the Global stream, so a 0.5
second poll rate might be a little too aggressive? ;)

Kosso

**Comment by ajmckee** [comment]
I agree, it was a tad agressive. Not intentional however, human error within config. Period in wrong place. 

Appnetstats I'm not too sure how accurate that is, but yes, once every 5 seconds is fine, but we've refactored to take into account the rate limit headers and should be a little smarter with them going forwards.

**Comment by mxml-barmstrong** [comment]
You can see our documentation on rate limits at https://github.com/appdotnet/api-spec/blob/master/limits.md
