### ISSUE TITLE
Can't star a repost?

### ISSUE THREAD

**Issue by fwanicka** [appdotnet/api-spec#188]
What is the reasoning behind preventing starring a repost?

**Comment by mthurman** [comment]
The docs are coming for all this stuff, but we want reposting to be more of a routing mechanism. If you want to star a post, or reply to a post, you aren't staring or replying to the fact that it was reposted, you're starring/replying to the original content.

Reposts are mostly a delegate object pointing to the real content, not content that is by itself important.

**Comment by mthurman** [comment]
Going to cross post this thread and close this issue: https://alpha.app.net/mthurman/post/411727
