### ISSUE TITLE
List which of my posts have been starred or reposted

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#191]
Currently, I can see how many stars and reposts a specific post has. I can also see who has starred or reposted a post. 

What I can't (easily) do, is see which of my posts have been starred or reposted.  I could pull in a few hundred of my post and filter by "num_stars > 0" but that doesn't seem very efficient.

I would like

```
https://alpha-api.app.net/stream/0/users/[user_id]/starred
```

and

```
https://alpha-api.app.net/stream/0/users/[user_id]/reposted
```

To return a list of posts made by the user which have been starred / reposted by others.

And, as I'm in an asking mood - being able to sort from high to low would be nice :-)

**Comment by jaredcwhite** [comment]
Maybe there's already this feature but I'd like to be able to get a list of my own posts that I have starred. Currently I'm showing my App.net posts on the profile generated by my web publishing software (http://jaredwhite.com) but it'd be nice to filter out my posts that aren't starred and only show starred ones. That way I can "feature" which posts I want to include.

**Comment by mthurman** [comment]
@jaredcwhite Right now you can either 1) get your posts and filter based on you_starred or 2) get all your stars and filter based on user (https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#retrieve-posts-starred-by-a-user)

**Comment by jaredcwhite** [comment]
Thanks @mthurman I'll take a closer look.

**Comment by orianmarx** [comment]
We've implemented this as a stream of Interactions. Documentation is here: http://developers.app.net/docs/resources/interaction/

Performing more advanced filtering of this data is probably a good opportunity for a third party service.
