### ISSUE TITLE
Filters based on Annotations

### ISSUE THREAD

**Issue by guscost** [appdotnet/api-spec#192]
We should be able to create a filter for a user that filters a stream based on post annotations. This would be essential for a service like AppAnnotate which would have to annotate posts with hidden URL identifiers and then create filters which would display the filtered streams on each webpage in a browser. Here's the suggested addition to the filter object:

<pre><code>{
    "data": [
        {
            "id": "1",
            "type": "show",
            "name": "On the go",
            "user_ids": ["1", "2"],
            "hashtags": ["sf"],
            "link_domains": ["app.net"],
            "mention_user_ids": ["1"],
            "annotations": [
                {
                    "type": "com.example.uniqueid",
                    "value": "ZawtGHuBTz57Y8pN0ytlQoHbrKu"
                }
            ]
        },
        ...
    ],
    "meta": {
        "code": 200
    }
}</code></pre>

Should a filter support an array of annotations like this, or should each filter id be limited to using a single annotation?

**Comment by tonymillion** [comment]
I'd like a filter for annotations too. I suggest however, that I'm only interested in being able to set a list of annotations I'm interested in seeing ("Type" field) the data I'll parse for sanity myself.

(and thus it should be fairly trivial to implement too)

// long winded way of saying +1

**Comment by tonymillion** [comment]
I'd had a chance to think about this and I think for my purposes this isn't what I want. New issue!

**Comment by orianmarx** [comment]
@guscost you should be able to do this with the current capabilities of Filters / Streams, so I'm closing this thread.
