### ISSUE TITLE
Extended text annotation

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#193]
I think a general extended text annotation would be useful, for more complex conversations, among other things.  The simplest approach would be to have the existing 256-length text be the "above the fold", and then have something like:

``` javascript````
{
    "type": "net.app.core.extended_text",
    "value": {
        "extended_text": "Further, I think ...",
    }
}
```

Good clients would let posters choose the break point between text and extended_text, much as some blogs do (with Read More...), rather than arbitrarily partitioning at 256.

The downside of doing this as is is that extended_text wouldn't be parsed for links, mentions, etc.

An interesting option (albeit using some space in responses) is to let annotation designers designate fields that should be parsed for entities the same way as text.  extended_text would then use that.  The entities would come back somewhere inside the annotation, and client developers wouldn't all have to reimplement this parsing.

**Comment by orianmarx** [comment]
I'm closing this thread with wontfix not because we're opposed to an extended text annotation but because this particular example is suggesting we make it a core annotation, which we won't.
