### ISSUE TITLE
Users Followers/Following Endpoint

### ISSUE THREAD

**Issue by jdscolam** [appdotnet/api-spec#195]
I was looking at the documentation, and the rules around the followers/following endpoints are a bit obscure.  Can we now send in generic parameters into those endpoints?  Please advise.

**Comment by mthurman** [comment]
You can send in the pagination parameters (`since_id`, `before_id`, `count`) if you have the `follow_pagination` migration enabled. https://github.com/appdotnet/api-spec/blob/master/migrations.md#current-migrations

**Comment by jdscolam** [comment]
Alright, I do have it enabled, but does it function like the general
parameters on posts, or something different?

----- Original message -----

**Comment by mthurman** [comment]
It functions the same way. Make sure that the parameters you are passing to since_id and before_id come from the `meta` envelope of a previous request, not from introspecting the `data` list.

**Comment by jdscolam** [comment]
Okay, I'll refactor #Rapptor to work appropriately.  May take me a day
or two :).

----- Original message -----
