### ISSUE TITLE
Allow mentions without text

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#198]
Per [the docs](https://github.com/appdotnet/api-spec/blob/master/objects.md#machine-only-posts) machine-only posts should not contain text.

However, posts need text to include a mention.

That means annotated posts with mentions can not be machine-only.

With the new JSON create post format, it should be feasible to allow programmatic mentions without text.

**Comment by mattflaschen** [comment]
It should allow mentioning multiple users in a single post.

**Comment by berg** [comment]
This is done and shipped:

https://github.com/appdotnet/api-spec/blob/master/objects.md

Look for "mentions in machine only posts"
