### ISSUE TITLE
UI: no char count in new message box on iOS/iPad browsers

### ISSUE THREAD

**Issue by feorlen** [appdotnet/api-spec#200]
When I go to post a new message, I don't get a character count while I'm typing if I'm using iOS on iPad. I've tried this on mobile safari, mobile icab and dolphin, all on iPad with iOS 5. my desktop Firefox is fine.

**Comment by orianmarx** [comment]
We had some bugs with the character counter on the iPad. Given that client development is a low priority for us and we aren't going to attempt to fix this any time soon, I'm closing this thread.
