### ISSUE TITLE
Option to batch follow emails over longer periods

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#201]
I do want to receive the follow emails for now, but they're too frequent.  I can see they're already batched, but I still received 5 yesterday alone.

A clear option for how often to receive this would be welcome.  E.g.:
1. Never
2. Monthly
3. Weekly
4. Daily
5. Immediately

**Comment by orianmarx** [comment]
As the user base grows we may revisit this but currently we have no plans change our "new follow" email batching behavior so I'm closing this thread.
