### ISSUE TITLE
Detect email addresses and add to annotations as mailto:

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#202]
In this post by @daltonc - https://alpha.app.net/dalton/post/590936 - the text is

```
@125f8 reporting ToS violations or any other kind of concern can/should be emailed to support@app.net
```

However, support@app.net is rendered as a username not an email address

support _@app_ .net

With the entities looking like

```
[mentions] => Array
            (
                ...

                [1] => Array
                    (
                        [id] => 6532
                        [len] => 4
                        [name] => app
                        [pos] => 93
                    )

            )
```

What it _should_ be IMHO, is a link entity

```
[links] => Array
            (
                [0] => Array
                    (
                        [len] => 15
                        [pos] => 85
                        [text] => support@app.net
                        [url] => mailto:support@app.net
                    )

            )
```

**Comment by orianmarx** [comment]
We should hopefully have all our bugs with email addresses where usernames were being parsed out of them now squashed. We won't be adding an email entity as these generally get linkified on mobile devices displaying plain text anyway and don't come up very often in posts to begin with. Of course on the client side you are free to run your own regex to linkify email addresses.
