### ISSUE TITLE
Endpoint to get all posts which contain a particular set of annotations type.

### ISSUE THREAD

**Issue by tonymillion** [appdotnet/api-spec#203]
I've been looking into Filters and I dont think its the kind of thing I'd want for Rivr to function (i.e. the rivr streams). Currently Rivr streams use a hashtag to find posts of a particular type, this would be better served by doing a search on all posts using search params - something like :

```
/stream/0/posts/byannotation/
```

Where we can pass in a JSON blob (rather like the new post API) that defines the annotation types we are interested in seeing

```
{
  types:["net.extendr.photo", "com.hashpan.picture"]
}
```

This would scan "type" fields of the annotations in posts and return the post if a match is found (effectively a SQL IN clause).

**Comment by simondlr** [comment]
As far as I understood Filters, this should be included. Adding an annotation type in the filter object.

Can anyone give clarification on this?

**Comment by tonymillion** [comment]
As I understand it it would require an app to create a specific filter under each of the users accounts who use the app - to me that seems slightly overkill.

**Comment by simondlr** [comment]
Ah yes. That is overkill. So, allowing apps to search for posts with certain annotations, AND filtering a user stream on annotations would be nice yes. Without resorting to filters, as creating one for each user seems a bit more verbose.

**Comment by mattflaschen** [comment]
Either filters or ad hoc (like this issue) would probably work for my app, but ad hoc is certainly simpler.  /byannotation/ should work for any stream, though (e.g. mentions, users/me/posts, etc.)

**Comment by tonymillion** [comment]
Just to add to this something I just realised, it could use the _exact_ same tech as the hashtags do as if I tagged the post text with #net.app.core.geolocation it would be extracted as a hashtag then I could use the posts containing hashtag API to get it back..

The "posts containing annotation" could do the exact same thing.

**Comment by romainpiel** [comment]
I'm also looking for this feature. I'm planning to make an app.net client based around music annotated posts and I'd love to have this request.

**Comment by habitatus** [comment]
Any update from ADN team on this one?
