### ISSUE TITLE
Real-time api

### ISSUE THREAD

**Issue by anythingmachine** [appdotnet/api-spec#205]
This is more of a suggestion than an issue.  I would love an interface more similar to Twitter's long connection than PubSubHubbub-like server-side messages... preferrably one that can even be directly subscribed to from the client (both javascript and through native apps).

I would love to build apps on App.net in the way I would build an app on PubNub

**Comment by orianmarx** [comment]
We've committed to supporting PubSubHubbub and some other related specifications: http://daltoncaldwell.com/a-response-to-brennan-novak

Timeframe still to be determined :) I am going to close this thread though as it's not really an outstanding issue.
