### ISSUE TITLE
Bug in current API with starred posts by user?

### ISSUE THREAD

**Issue by operatorjen** [appdotnet/api-spec#206]
Not sure if this is a bug or something I missed, but if I have my app set to the current API (not legacy), and I make a GET call to this:

`https://alpha-api.app.net/stream/0/users/<USER_ID>/stars?before_id=<POST_ID>&access_token=<ACCESS_TOKEN>`

I will retrieve an incorrect response back. This works as expected (correct response) if I use the same format for user mentions, feed, global feed - it only behaves incorrectly on stars.

Any idea?

**Comment by berg** [comment]
Pagination for this endpoint is based upon the internal star_ids exposed in the `meta` object in the response envelope. The native ordering of this endpoint is based upon the order starred – so we don't use post_ids for pagination.

I've just tested and it seems to work properly. Feel free to reopen if that isn't what you're seeing.
