### ISSUE TITLE
Need an endpoint that accepts array of Post Ids

### ISSUE THREAD

**Issue by fwanicka** [appdotnet/api-spec#207]
Is there any plan to offer an endpoint where an array of Post Ids could be passed in and posts could be returned in that order?

I am considering grabbing the global feed and putting it into a database so I can do keyword searches (as other have) and properly built conversations/threads in a treeview type of structure (instead of chronological).

I can do that and pass the posts to my client app, but the post data (number of stars and reports) will be stale, and the data that is specific to the authenticated user (you_follow, you_muted, etc.) would be incorrect.

So, what I really need is to build up the list of Post Ids in the order I need and pass that as an array to the API and get back the posts in the same order.

The only other way to do it would be to get them one at a time, which will be slow and will potentially cause end users to hit rate limits.

**Comment by jdscolam** [comment]
+1 on this.  The duplication of storing every post on ADN is long-term insanity.  Sorry to be so openly opinionated -_-;

**Comment by fwanicka** [comment]
After discussing this with @tonymillion, getting the posts back in the same order as the Ids passed would be nice, but not an requirement if it would add undue server load, or take extra time to implement. I could do the sorting on my end if necessary.

**Comment by berg** [comment]
This is now available:

https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#retrieve-multiple-posts

Works for users, too. Unfortunately, it's not sorted, but it should be easy enough to extract the IDs from the returned objects.
