### ISSUE TITLE
Can sign up while signed in

### ISSUE THREAD

**Issue by tgvashworth** [appdotnet/api-spec#211]
Not sure this should be possible.

When this occurs, it causes a weird session or maybe caching issue where it looks like you're still logged into the account you were in before, not the newly signed up one, but when you post it comes from the new account.

**Comment by berg** [comment]
This could happen if you've got a tab open, open a new tab, sign up, and post in your old tab -- when you post it's just using your session's current cookies. Not sure we can fix this.

**Comment by mattflaschen** [comment]
You could render the username into a hidden field/data attribute.  When you post, include the hidden field too.  On the server, the post only succeeds if the form field and actual username (determined from session) match.  Otherwise, the message is redisplayed in the input box.
