### ISSUE TITLE
Account name should be shown on oAuth permissions screen

### ISSUE THREAD

**Issue by jaredcwhite** [appdotnet/api-spec#212]
Now that developers can set up multiple accounts, that brings up the issue where when you authorize a new service to connect to App.net and the permissions dialog comes up, it doesn't actually say what account you're logged in as. So unless you can simply remember (yeah, right), you could be authorizing the wrong App.net account. It should probably say something like "[xyz service] requests permission to access your [@loggedinuser] App.net account"

**Comment by kosso** [comment]
+1

I agree with this. It needs one of those "not you?" things. Or simply the
top right corner avatar to easily show 'who' 'you' are.

**Comment by berg** [comment]
Yes, this makes sense. I'll add this to the list.

**Comment by orianmarx** [comment]
The account you are currently logged in to is now displayed on the OAuth permissions page.
