### ISSUE TITLE
Share on ADN via url

### ISSUE THREAD

**Issue by unscripted** [appdotnet/api-spec#214]
I'm working on ways to share posts to @adn via WordPress (or any other website) and I'm curious what is needed to make something like Twitter's share via url for ADN? (e.g. https://twitter.com/intent/tweet?text=This%20is%20a%20sample&url=http%3A%2F%2Funscriptedlabs.com).  Google+ and Facebook also have similar features.  

I've crawled through the API to see of a way that might work but it seems this is something that would need to be hosted on ADN's side.  That way someone isn't having to authorize the website they're visiting just to share.

**Comment by mattflaschen** [comment]
I think voidfiles already [wrote this](https://github.com/voidfiles/share-on-adn/blob/master/index.html), using the standard OAuth API.  You don't authorize the website you're visiting/sharing, just the share script.

Other people can write their own, of course.  They might have distinct features, like embedding images from the story.

**Comment by voidfiles** [comment]
@unscripted We want to support web intents (http://webintents.org/) for sure. This would allow for people to create buttons that you are talking about. 

@mattflaschen Share on ADN right now is a little bit more focused on individuals wanting to share any webpage on app.net. I think @unscripted is talking more about letting websites create share buttons for there content that app.net users could use.

**Comment by voidfiles** [comment]
We launched the first part our web intent support.  You can read more about it here https://github.com/appdotnet/api-spec/blob/master/intents.md but this should help you create a share on adn button.

**Comment by unscripted** [comment]
@voidfiles Sorry that I some how missed this.  Starting messing with it tonight and it works perfectly.

Cheers!
