### ISSUE TITLE
Domain is doubled for anchored links in RSS

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#220]
In user RSS feeds (e.g. https://alpha.app.net/adnapi/post/1091562), the domain hint for anchored links is doubled.  E.g. it shows:

``` xml
<title>adnapi: &gt;&gt; @mthurman: We're rolling out new features from the #hackathon. Check out our new language annotation [github.com] [github.com] and a new way to get multiple posts [github.com] [github.com] or users [github.com] [github.com] at once #rollout</title>
```

**Comment by mthurman** [comment]
This was a problem with reposting a post that had custom entities (not specifically with RSS). Old posts won't change, but this is fixed going forward after our latest rollout.
