### ISSUE TITLE
Service status page

### ISSUE THREAD

**Issue by zerodistraction** [appdotnet/api-spec#222]
Although the service is reliable right now, in the name of openness with customers, I think it's a good idea to implement a status update page (perhaps using Pingdom?). This way, both regular users and developers can keep tabs on any service related problems.

**Comment by ghost** [comment]
This would be nice to have, and it would also be great if it would email us when their is an outage, so we can tell our users when that has happened and why.

**Comment by orianmarx** [comment]
We will be getting one of these up, but we don't have a timeline for it yet.

**Comment by aknapp** [comment]
Finally got around to doing this: adnstatus.net

Also, follow @adnops on app.net for more updates.
