### ISSUE TITLE
Option to exclude one's posts from search engine indexing.

### ISSUE THREAD

**Issue by berklee** [appdotnet/api-spec#223]
Hello,

I just noticed that Google is indexing App.net posts within minutes. I don't want my posts to be private, but I also don't want to have them indexed by Google or any other search engine within a few minutes, that feels a bit creepy.

So I'd like to suggest the option to filter out the posts that you make from the data presented to search engines. I understand this adds a layer of complexity to your queries and recognise this would not be a top priority feature request. Nevertheless, I'd like this feature. I'm willing to write the necessary code if that helps.

**Comment by orianmarx** [comment]
Now that we've released the Messaging API developers can build clients that support sending private messages, and these will not be indexable by search engines. Posts will remain completely public and users should consider anything they post on the public web to be potentially indexable by search engines. 

Also, it would be especially complex for us to prevent indexing of some posts and not others given that posts often appear in threads, and then there would be a conflict as to whether we let the entire thread get indexed or not.
