### ISSUE TITLE
Online Status User Annotation

### ISSUE THREAD

**Issue by swhitley** [appdotnet/api-spec#227]
This annotation indicates user availability.

This is a first draft.  Subsequent drafts will appear in the comments.

``` json
{
    "type": "temp.status",
    "value": {
        "status": "Away",
        "details": "Off to Hawaii!!!",
        "post_id": 9874177
    }
}
```

status - Any value is allowed, however, we will specify a standard list so developers can present a picklist.
details - Additional information (256 standard) about the status.
post_id - A post that provides additional details about the status.

Standard Status List 
The list below was created after reviewing several applications with similar features.

Available
Not Available
Do Not Disturb
Be Right Back
Away
Custom Status

**Comment by mattflaschen** [comment]
Is the post_id necessary?  It might be more natural to put the additional details in the current post, which you actually can't refer to by post_id.

**Comment by swhitley** [comment]
I agree, post_id may not be practical.  I just included it for the sake of discussion.

**Comment by beccadax** [comment]
I would recommend the "status" field be limited to a standardized, language-independent set of constants, such as:
- available
- not_available
- away
- do_not_disturb
- be_right_back
- custom_present
- custom_absent

A separate "custom_description" field would provide text for the "custom_present" and "custom_absent" statuses.  (Alternatively, drop the custom_\* statuses and allow the "custom_description" field to be used with any status.)

I would also question the number of away statuses we have here. What's the difference between "not available", "away", "do not disturb", and "be right back"?

Finally, one status that I see in a lot of IM clients is "idle". Should we consider including an idle status, or would that be inappropriate for App.net?

**Comment by beccadax** [comment]
One more thing I just thought of. What is the recommended behavior when you want to change your status? Should you delete the old status, or leave it in place? Are there cases (like the user hitting an "undo" button) when deletion would be appropriate? We should be clear about these behaviors.

**Comment by swhitley** [comment]
``` json
{
    "type": "temp.status",
    "value": {
        "available": false,
        "text": "Off to Hawaii!!!"
    }
}
```

``` json
{
    "type": "temp.status",
    "value": {
        "available": true,
        "text": ""
    }
}
```

The original list came from a combination of Skype and some other IM clients.  However, many modern clients simply show two standard indicators (available or busy).  Idle may make sense while you're waiting for keyboard input in a real-time exchange, and real-time exchanges may be possible using  streaming, but I think that can be handled with 'available: false, text: "Idle"'. 

I've altered the proposed spec to use a language independent status indicator.  You're either available or you're not.  The status text field can then contain any text you like.  As a guideline, clients may choose to only display the first 20 characters (similar to Google Chat).

There is a single status annotation.  If you perform an update, it wipes out your previous status.  Clients could elect to save the previous status entries and present that information if desired, but it would not be required.

**Comment by orianmarx** [comment]
I actually don't see what's wrong with the first approach, a generic status field with arbitrary text? Another thing you might want to add is a timestamp for when the status would set.

**Comment by swhitley** [comment]
``` json
{
    "type": "temp.status",
    "value": {
        "available": true,
        "text": "",
        "updated_at": "2012-07-16T17:25:47Z"

    }
}
```
- Updated to include a timestamp.

The first two from the list are still represented in the "available" property.  We're just removing the last three.  They're sort of arbitrary anyway.

available
not_available
x away
x do_not_disturb
x be_right_back

**Comment by orianmarx** [comment]
I suppose the last three can be representing the text field anyway, and are all subsets of not_available.

**Comment by beccadax** [comment]
Wait, this is a user annotation, not a post annotation? Huh, that changes things a bit. post_id may then make sense, or it may make sense to allow you to attach any relevant URL (which might be a post or might be something else). updated_at would make good sense as well, unless that data is somehow provided by the API, which I'm guessing isn't the case.

## Away vs. Idle

The difference I see between idle and not available is that "not available" is a state set by the user, while "idle" is heuristically determined by a computer. You don't set idle yourself—the computer notices that you haven't used it in a while and decides you must be idle.

That doesn't necessarily make sense when you can have several different clients accessing the same account, though—you may be idle on your computer at home but active on your phone. Maybe the answer is to have a separate annotation that is regularly updated by any client that considers itself active:

```
{
    "type": "temp.last-active",
    "value": {
        "active_at": "2012-07-16T17:25:47Z"
    }
}
```

If active_at exceeds some agreed-upon threshold (fifteen minutes, say), clients should assume the user is idle.  We then leave the whole concept of idle state out of the status annotation and leave it to this annotation instead.

## Standard statuses

There's something very appealing about the simple boolean "available" status, but there _are_ reasons not to simplify it that far:
- Standard statuses can be translated into your own language by your client. A bilingual user need not choose between using "do not disturb" and "おやすみモード"—other users' clients can translate for them automatically.
- Having a list of universally-understood statuses encourages people to use the same ones as everyone else. This helps ensure that everyone knows what each status means.
- Clients could help users understand what each standard status means, e.g. by showing tooltips or showing some sort of warning message.
- Machines can understand standardized statuses and do intelligent things with them, such as showing graphical indicators of a user's status, notifying you when a user switches to a certain status, or changing the client's own behavior (for example, silencing notifications).

My point earlier was not that there were far too many statuses, but that the differences between them were ill-defined. As a first cut, here are the statuses I would suggest we support and what each one means:
- "available": User is essentially soliciting messages.
- "busy" or "do_not_disturb": User can see messages, but is doing something else and does not wish to be unnecessarily disturbed.
- "away": User will not see your message.
- (Possibly) "be_right_back": User will see your message shortly.

Users could also specify custom text to replace whatever the client would show for that status by default. This would be available for all statuses.

**Comment by swhitley** [comment]
I've done some additional research and looked at the XMPP spec.  

http://tools.ietf.org/html/rfc6121#section-4.7

The samples below represent the _presence_ standard from XMPP.  "Type" is not included, but it can be derived from the "available" property.

Available

``` json
{
    "type": "org.xmpp.presence",
    "value": {
       "available": true,
        "show": "",
        "status": "",
        "link": "",
        "updated_at": "2012-07-16T17:25:47Z"
    }
}
```

Not Available without Show

``` json
{
    "type": "org.xmpp.presence",
    "value": {
       "available": false,
        "show": "",
        "status": "Be right back",
        "link": "",
        "updated_at": "2012-07-16T17:25:47Z"
    }
}
```

Not Available with Show

``` json
{
    "type": "org.xmpp.presence",
    "value": {
        "available": false,
        "show": "xa",
        "status": "Off to Hawaii!!!",
        "link": "http://myvacation.com",
        "updated_at": "2012-07-16T17:25:47Z"

    }
}
```

Possible [show] values:

   o  away -- The entity or resource is temporarily away.
   o  chat -- The entity or resource is actively interested in chatting.
   o  dnd -- The entity or resource is busy (dnd = "Do Not Disturb").
   o  xa -- The entity or resource is away for an extended period (xa =
      "eXtended Away").

**Comment by swhitley** [comment]
In trying to get to a final cut, I've simplified the XMPP version to make it easier for developer adoption.  This version takes into account feedback from @brentdax and @orianmarx.  It's important to note that a standard XMPP presence stanza could be generated from this spec.

Standard Presence Codes  (Combination of feedback from @brentdax  & XMPP standard)
- available -- The entity or resource is open to receiving messages and is likely to respond.
- busy -- The entity or resource is open to receiving messages, however, a response should not be expected.
- away -- The entity or resource is temporarily away.
- dnd -- The entity or resource is busy (dnd = "Do Not Disturb").  This is similar to busy, however, it is more emphatic. The entity or resource is not open to receiving messages.
- xa -- The entity or resource is away for an extended period (xa = "eXtended Away").

Note:  The XMPP 'type' attribute can still be derived from the presence code.  We are using all of the standard 'show' codes from XMPP except 'chat' -- which can be assumed in the 'available' code.  The 'show' attribute has been changed to 'code' for clarity.

A custom status can be generated by using codes of 'available' or 'busy' with a custom "status."  Please review the functionality of Google Talk for an example of implementing the custom status UI.

``` json
{
    "type": "org.xmpp.presence",
    "value": {
        "code": "xa",
        "status": "Off to Hawaii!!!",
        "link": "http://myvacation.com",
        "updated_at": "2012-07-16T17:25:47Z"

    }
}
```

``` json
{
    "type": "org.xmpp.presence",
    "value": {
        "code": "available",
        "status": "",
        "link": "",
        "updated_at": "2012-07-16T17:25:47Z"

    }
}
```

``` json
{
    "type": "org.xmpp.presence",
    "value": {
        "code": "busy",
        "status": "Zzzzzzzzz",
        "link": "",
        "updated_at": "2012-07-16T17:25:47Z"

    }
}
```

**Comment by orianmarx** [comment]
@swhitley I'd like to close this issue. Can you reopen it on https://github.com/appdotnet/object-metadata and make a reference to appdotnet/api-spec#227 to create a pointer back here if you want to keep it active?

**Comment by swhitley** [comment]
@orianmarx 

I was a little confused.

How about the following?

@swhitley I'd like to close this issue. If you'd like to continue this discussion, please open a new issue on https://github.com/appdotnet/object-metadata.

Include a reference to appdotnet/api-spec#227 to link back to this discussion.
