### ISSUE TITLE
Unified Stream not a strict union of Personalized and Mentions streams

### ISSUE THREAD

**Issue by DonaldHays** [appdotnet/api-spec#228]
There's a narrow edge case where a specific kind of post is omitted from the Unified stream, but shows up in the Mentions stream.

When no parameter is specified for "include_directed_posts", the specification states that the Personalized stream defaults to false, and all others default to true. So, if user A (who I follow) sends a directed post to user B (who I do _not_ follow), and user A mentions me in the post, that post will show up in my Mentions stream, but not my Personalized stream. All this is correct behavior.

With the Unified stream, on the other hand, if I don't include a parameter for "include_directed_posts", then I won't get the post I described above. I don't think that's correct behavior, and it presents a problem for the app I'm writing.

Our app allows the user to enable or disable "Unified timeline" mode, and also allows the user to enable or disable "show directed posts in Personal stream". If the user has enabled Unified timeline, but disabled show directed posts, they should still see _all_ posts that mention them in the Unified timeline, including posts directed to other users, same as the Mentions stream would show in a non-Unified timeline mode.

If I try to work around this issue by settings "include_directed_posts" to true, however, then the unified timeline will show all directed posts the people I follow make, regardless of whether or not they mention me. Because of this, I don't believe it's possible to get a Unified timeline stream that accurately represents a union of the default directed post behavior of both the Personal and Mentions streams.

**Comment by mthurman** [comment]
Sorry about that--we just rolled out a fix for this.
