### ISSUE TITLE
Post count should match actual post count

### ISSUE THREAD

**Issue by Critter** [appdotnet/api-spec#229]
If you look at my profile /critter, it just looks like bad math. Deleted posts, should be deleted from the total post count.

**Comment by mthurman** [comment]
I'm not saying we won't change this behavior (and I'm not saying that we will) but I'm going to link to a recent exchange about this exact topic for context: https://alpha.app.net/mthurman/post/1400917

**Comment by mattflaschen** [comment]
Since it's still public that you made a (now deleted) post, it makes sense to make the full total available.  But the total excluding deleted posts is also useful.  I suggest providing both counts after issue #96 is fixed (FYI, I suggest opt in for fields you want).

**Comment by orianmarx** [comment]
Since we don't plan on changing this behavior any time soon, if at all, I'm closing this thread.

**Comment by mthurman** [comment]
We've made this behavior change: user.counts.num_posts now only refers to the number of undeleted posts for a user.
