### ISSUE TITLE
Why is a JSON-based format using snake_case?

### ISSUE THREAD

**Issue by sporkmonger** [appdotnet/api-spec#23]
Given that you're using _JavaScript_ Object Notation, shouldn't you be using JavaScript naming conventions? They're easy enough to convert in most server-side languages to something that's more idiomatic to the backend processing language, if that's necessary, but it's a particularly obnoxious step to have to take in any kind of client-side code.

**Comment by matthewp** [comment]
Agreed, although as a JavaScript developer I've come to accept that APIs revolve around Ruby developers.

**Comment by sporkmonger** [comment]
I'm a Ruby developer. It shouldn't be snake_case. :-P

**Comment by berg** [comment]
Thanks for your feedback. While I can appreciate why there might be divergent opinions here, we're going to use underscores in the key names.

In particular, not having to worry about whether to use `fullHtmlContent` versus `fullHTMLContent` puts it over the edge.
