### ISSUE TITLE
Should be a way to indicate extra text added by App.net in a post

### ISSUE THREAD

**Issue by beccadax** [appdotnet/api-spec#230]
When you create a post with embedded link attributes, App.net inserts a domain name in square brackets into the text. There's no way to tell this artificially-injected text from the text the user provided; without that knowledge, clients can't reliably style this text differently or generate a new post based on the text of an existing one (for example, quoting a post).

It'd be helpful if post objects included enough information to reconstruct the unaltered text and entities. I can think of a few approaches:
1. A new entity type that would mark artificially-added parts of the text. (This could also be used to mark the prefix on reposts.)
2. A parallel set of pos/len attributes in link entities indicating the area of added text.
3. A flag on the post indicating whether the link attributes in it were provided by the poster or generated by App.net. Clients could then manually scan for the domain names.
4. A separate, unaltered copy of the text and entities embedded in the post.

**Comment by mattflaschen** [comment]
This same issue applies to description (which now supports custom links as well).  Of course, editing the description repeatedly is common, and requires stringifying (in Noodle's case to Markdown) and parsing back and forth.

Until this is in place, we will need to all write our own regexes or equivalent to strip the bracket parts ourselves.

I can make a separate issue for description if desired.

**Comment by orianmarx** [comment]
I agree this is a bit of an issue and also needs to be handled better in the documentation as we are okay with you stripping out this additional text _if_ there are other anti-phishing techniques in place in your app (say showing the url in a "footnote" or on rollover).

**Comment by mthurman** [comment]
We just rolled out the `amended_len` property for links that should take care of this use case http://developers.app.net/docs/meta/entities/#links
