### ISSUE TITLE
Ability to post multiple stream markers at once

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#233]
I am / will be POSTing the currently-appropriate stream markers when users suspend my app. It would be convenient to be able to send them all in one request as a JSON array, like this:

[{"name": "global", "id": 1}, {"name": "my_stream", "id": 2}, {"name": "mentions:440", "id": 3}]

but this currently returns an error, "Bad Request: JSON is not a valid object." Just sending any of these markers singly works as expected.

Firing off three requests in this case isn't a big deal, but allowing for an array of objects would be a convenient way to bundle some of these requests together, particularly when network resources are constrained. Thanks!

**Comment by mthurman** [comment]
Fixed: https://alpha.app.net/mthurman/post/1729013
