### ISSUE TITLE
User search pagination data

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#236]
I don't seem to be seeing any pagination data in the response for user searches. Example:

https://alpha-api.app.net/stream/0/users/search?q=Twitter

Meta currently contains only the status code.

If I manually add various returned userIds with before_id and since_id, the returned data set is the same. (I understand that before_id and since_id aren't necessarily ids from the returned set, nor are these parameters referred to in the documentation, but figured I'd give it a shot to see if it affected the returned data at all.)

For now, I can just crank the count parameter up to 200, but if it's possible, being able to paginate this data at some point would be handy.

**Comment by orianmarx** [comment]
User search is built differently than other endpoints so we won't be supporting any paging parameters on it. I'm closing this for now but if / when we reach the scale that this becomes an actual issue feel free to reopen it.
