### ISSUE TITLE
User id cannot be "me" when requesting avatar or cover image

### ISSUE THREAD

**Issue by mattrubin** [appdotnet/api-spec#244]
In the [Users spec](https://github.com/appdotnet/api-spec/blob/master/resources/users.md#retrieve-a-users-avatar-image) for retrieving an avatar image, the options for the `user_id` parameter are listed as a user id number, a `@username`, or `me`.

Using a user id number or `@username` produces the correct result:

> [`GET https://alpha-api.app.net/stream/0/users/1/avatar`](https://alpha-api.app.net/stream/0/users/1/avatar)
> [`GET https://alpha-api.app.net/stream/0/users/@dalton/avatar`](https://alpha-api.app.net/stream/0/users/@dalton/avatar)

Using `me` returns an error:

> [`GET https://alpha-api.app.net/stream/0/users/me/avatar?access_token=[...]`](https://alpha-api.app.net/stream/0/users/me/avatar)
> 
> ``` js
> {
>     "meta": {
>         "code": 405,
>         "error_id": "924f3f6f06394a1bbc6488a904c81cd9$6c10984086364ba414bf55a0e720941c",
>         "error_message": "Method not allowed. Please use: POST"
>     }
> }
> ```

This error is the same regardless of the `access_token`, and appears to have nothing to do with authentication.

**Comment by mthurman** [comment]
Sorry about this bug, it should be fixed now.
