### ISSUE TITLE
Detect Magnet Links

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#245]
Creating a post with a Magnet link produces unexpected behaviour.  Not only is the Magnet URI not detected properly, the ADN link detection algorithm adds in unwanted links.

For example https://alpha.app.net/edent/post/1938982

I've posted `magnet:?xt=urn:btih:fa692da0488aee23e5eb605a87be934ad7cec106&dn=Guy+Fawkes+and+Anonymous+mask&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A6969&tr=udp%3A%2F%2Ftracker.ccc.de%3A80`

Which adds these erroneous entities.

```
[entities] => Array
    (

        [links] => Array
            (
                [0] => Array
                    (
                        [len] => 28
                        [pos] => 107
                        [text] => 2Ftracker.openbittorrent.com
                        [url] => http://2Ftracker.openbittorrent.com
                    )

                [1] => Array
                    (
                        [len] => 22
                        [pos] => 154
                        [text] => 2Ftracker.publicbt.com
                        [url] => http://2Ftracker.publicbt.com
                    )

                [2] => Array
                    (
                        [len] => 19
                        [pos] => 195
                        [text] => 2Ftracker.istole.it
                        [url] => http://2Ftracker.istole.it
                    )

                [3] => Array
                    (
                        [len] => 16
                        [pos] => 235
                        [text] => 2Ftracker.ccc.de
                        [url] => http://2Ftracker.ccc.de
                    )

            )
```

**Comment by orianmarx** [comment]
We're not going to add support for magnetic links, but you could instead pass this data in an annotation. The urls we are parsing in this case are "wrong" from an intent perspective but they're right for our url parsing scheme which detects urls surrounded by punctuation. This is one of those things it's likely impossible to get right in all situations.
