### ISSUE TITLE
Default cover and avatar images

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/api-spec#246]
I noticed that for a new user, the default avatar and cover image are set to https://d2rfichhc2fb9n.cloudfront.net/image/4/X1p8y7MSNnMKbPq2Oe7-TPwEBzgDDwkrw7Cy9-iBH96aL2gycU8siG0lF6fI7ZP0yYh5iiExlK5pfCMghlN8Er-KvLDnBMIlH_KM_ZjlHsi01f5bodSkvsOf6JRDI_Xsb51_EQjHcbXpPqgBvYvjWxVNRvA and https://d2rfichhc2fb9n.cloudfront.net/image/4/_qtbudHpXtjys3CJVSRcSFcOYtCeY5wbD_tXdTiuhTAUV3vfYbKcF8TkvJRJiEbdDaRsUuChlN1rHzNDHm2Bj6OJ4y1LKkNQW64xqfLCUkjBy60_4D7lWlDpXKBZVN45MpoIFOVWHqIFNsvS0SRyUlA4lyA actually in the response of the user.

Would it make more sense to have these values/objects as null so that each individual app can display their own default avatar/covers (without having to catch for specific urls which are most likely subject to change)

**Comment by tonymillion** [comment]
Or even better, not send them at all for new users - null is a HORRIBLE thing to deal with and it'll just crash most iOS clients off the bat.

**Comment by scruffyfox** [comment]
yeah, +1 that

**Comment by orianmarx** [comment]
We're planning to add booleans indicating whether or not these fields are currently set to our default images.

**Comment by berg** [comment]
This is done. Gotta update the docs, so I'm leaving this one open right at the moment, but:

``` js
"avatar_image": {
    "height": 89,
    "is_default": false,
    "url": "https://d2rfichhc2fb9n.cloudfront.net/image/5/wSBXRyjAVr-uhToeJ_91ZE7ZJcV7InMiOiJzMyIsImIiOiJhZG4tdXNlci1hc3NldHMiLCJrIjoiYXNzZXRzL3VzZXIvYWMvYzQvMTAvYWNjNDEwMDAwMDAwMDAwMC5wbmciLCJvIjoiIn0",
    "width": 88
}
```

**Comment by orianmarx** [comment]
Docs are updated.
