### ISSUE TITLE
Provide basic user information in the ACL user lists

### ISSUE THREAD

**Issue by simonwelsh** [appdotnet/api-spec#249]
The current ACL user lists only provide user IDs. This means almost every time a channel is retrieved, another request is made to get the user object for all those involved. I would like at least the username and display name returned along with the ID. Maybe even an option to return full user objects.

**Comment by tigerbears** [comment]
I second this wholeheartedly. At the very least, usernames or full names need to be available for efficient presentation, particularly on mobile. Firing off a bunch of secondary requests to retrieve this information to simply display an inbox is going to be brutal on a lot of users.

**Comment by mattflaschen** [comment]
I agree this makes sense. In the meantime, you can [retrieve multiple users](http://developers.app.net/docs/resources/user/lookup/#retrieve-multiple-users) in one request.

**Comment by tigerbears** [comment]
Aha! Forgot all about that endpoint. Useful. OK, I should be able to use that as a temporary workaround. Thanks. :)

**Comment by berg** [comment]
I believe you should only have to fire off a single additional request (per 200 unique requested users), so I'm going to close this, as we're trying to move towards smaller request bodies combined with a very small number of secondary requests.
