### ISSUE TITLE
non-integer based IDs

### ISSUE THREAD

**Issue by glenngillen** [appdotnet/api-spec#25]
Potentially a premature optimization, but it's something that's tricky to unwind later. What are your thoughts on making object IDs something like a timeuuid? It makes running in a distributed fashion easier, and potentially #22 too. I notice the datatype for objects ID is already described as an alphanumeric strring, but all example show it as a quoted integer. Might just be a case of clarifying the docs.

**Comment by abraham** [comment]
Is the [Object IDs](https://github.com/appdotnet/api-spec/blob/master/objects.md#object-ids) section the clarification you were looking for?

**Comment by mthurman** [comment]
We're definitely thinking ahead to this and thus, as mentioned, the spec clearly states that IDs are strings.

The fact that they happen to look like integers right now is an implementation detail that clients shouldn't have to worry about.
