### ISSUE TITLE
Provide recipient ids in Message data in the public Stream

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#251]
To be clear, I'm referring to this object: http://developers.app.net/docs/resources/stream/#message via the public Stream API.

iOS and other users will expect push notifications when receiving a private message. Right now the message's data includes the user who wrote the message, but the only recipient-oriented information that I can see is the channel_id for the message.

Unfortunately, determining who would be receiving that message, based on channel ACLs, gets pretty cumbersome. I can fire off a server-side request to grab that channel's ACL (once and then storing the result for immutable channels, or every time if it's mutable) or retain copies of all the channel creation / subscription messages and address notifications accordingly. (Channels created before one started to do that would be out of luck in the second scenario.)

It would be a huge help if, at least for the net.app.core.pm types, the user IDs of the recipients were included somewhere in that object; maybe in the meta dictionary? I can see how that would get impractical for certain message types, but at least for "true" PMs this would be a huge help to get us started. Thanks!

**Comment by berg** [comment]
I'm hoping that our discussion about the best way to handle this (LRU cache of channel subscriptions, refreshed intermittently or as needed) is going to suffice. I'm hoping that the small amount of temporary local state you're required to keep as part of this is going to be OK. If there's really no way you can make that work, let me know and we'll try to figure something out.

**Comment by tigerbears** [comment]
Yeah, I think it'll hold up for a while at the very least, thanks. Maintaining all channels constantly and forever was no bueno, but if hitting those endpoints as needed is OK then this should work. At some point things will scale to where rate limits would be an issue (5k "old" channels messaged in an hour) but that doesn't seem imminent.

**Comment by berg** [comment]
Cool. Going to close this for now for sanity's sake then. If you hit that rate limit, we'll have some champagne and then just raise it. ;)
