### ISSUE TITLE
Provide endpoint with all messages for logged in user

### ISSUE THREAD

**Issue by liGhun** [appdotnet/api-spec#252]
I would like to suggest an endpoint which returns a list of all messages for the current user like it is available for "my_stream" and similar. It should of course feature since and before parameters as well as a count parameter.

The only current way to be sure not to miss new entries is to get all channel Ids the user is subscribed to and then loop through them and fetch the messages. Quite much overhead I think

**Comment by berg** [comment]
Part of the reason why channels are efficient for certain applications is that we don't keep a fanned-out list of messages for each user. This does make rendering a set of channels a bit more difficult, but when combined with the mass-fetch endpoint for messages and pagination of the channels endpoint, it's not too hard to ensure that you've got everything.
