### ISSUE TITLE
Add means to fetch prior channel subscriptions or include more information in subscription deletions

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#255]
What I'm trying to do is to stop sending push notifications to a person who is no longer subscribed to a channel.

When a user deletes a subscription to a channel, the public stream includes a brief message indicating that subscription id "123" was deleted. No other information about the subscription is provided.

Here's an example:
{"meta": {"timestamp": 1355814436750, "is_deleted": true, "type": "channel_subscription", "id": "260"}}

In order to do anything with this, we have to have local copies of all channel subscriptions so we can remove that subscription's owner from the channel's distribution list. 

Maybe I'm missing something (again) but I'm unaware of a way to fetch the information for a channel subscription if one doesn't already have a copy of it. This may not seem like a big deal now (users could be asked to rejoin and requit a channel in a pinch, strange as that may be experience-wise - assuming they can rejoin that channel) but what about future efforts? There's already over a thousand subscriptions to catch up on.

Similarly, is there a more streamlined way in which we can do this? I have to say I'm not looking forward to retaining (indefinitely) local copies of every subscription object generated by a growing userbase. If it's at all possible to avoid more API roundtrips, that would be very helpful.

Barring the inclusion of read-authorized user ids in a Message message, perhaps the unsubscribe messages could include the relevant userid and channel id as well?

{"meta": {"timestamp": 1355814436750, "is_deleted": true, "type": "channel_subscription", "id": "260", "user_id" : "123", "channel_id" : "345"}}

Thanks!

**Comment by berg** [comment]
We shipped support for including information on deleted users and channels in the delete messages the week before last. Pretty sure I told you about this out-of-band, but for everyone else... ;)
