### ISSUE TITLE
Filter channels by type

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#259]
It would be great if http://developers.app.net/docs/resources/channel/subscriptions/#get-current-users-subscribed-channels allowed you to filter by channel type.

I think this is more scalable than post/message filtering.

**Comment by swhitley** [comment]
I agree.  If you're only interested in a specific channel type, you might not know which pages would contain them.  This would be particularly an issue where the person sends a lot of private messages and/or the custom types are not very active.

**Comment by mattrubin** [comment]
+1
My app is looking for all channels of a specific custom type for the user, so with the current endpoint, I'd have to examine every channel the user is subscribed to – possibly over multiple pages – to find the few I'm looking for.

**Comment by berg** [comment]
I don't think this'll be too hard to do, but I might be missing something. I'll see what we can do here. Definitely understand why this is useful.

**Comment by mthurman** [comment]
We just launched this: http://developers.app.net/docs/resources/channel/#general-parameters
