### ISSUE TITLE
Data Import from Other Platforms

### ISSUE THREAD

**Issue by astroak** [appdotnet/api-spec#26]
Allow App dot Net to import information, mainly contact information and images, from other social platforms. I believe a big concern for others, especially those who use social media on a daily basis, will be concerned of all the lost data from switching platforms.

appnet users: randyg

**Comment by paulmwatson** [comment]
With Twitter blocking the friends API for Instagram it's clear this is not only a technological hurdle to overcome.

(I'd also say it is not a critical issue to resolve. I came to Twitter cold, nothing imported.)

**Comment by astroak** [comment]
That's why i mentioned for daily users with large amounts of data. But I believe twitter does have a way to find friends via gmail, yahoo mail etc. Again, just making the transition a little easier.

This actually can be something later down the line when the user count picks up.

**Comment by mxml-barmstrong** [comment]
Thank you for your feedback. This will not be a part of our core API, so we will not be offering this. Our devs are welcome to implement cross-platform as they like.
