### ISSUE TITLE
Subscribed channels with unread messages

### ISSUE THREAD

**Issue by mattflaschen** [appdotnet/api-spec#260]
It would be great to have a query for [subscribed channels](http://developers.app.net/docs/resources/channel/subscriptions/#get-current-users-subscribed-channels) with unread messages.

If it's combined with filtering by channel type (#259), even better.

**Comment by swhitley** [comment]
+1

**Comment by berg** [comment]
To be clear, this would work the same way as the current channels endpoint, but it'd omit channels without unread messages, right?

**Comment by mattflaschen** [comment]
Correct, just use the stream marker to exclude ones where you've read everything.

**Comment by berg** [comment]
OK, got it. Not quite as easy as #259 but we'll give it a shot.

**Comment by orianmarx** [comment]
We added a general param for this to channel requests. https://github.com/appdotnet/api-spec/commit/6e51346406d3d99067b595b3b1de2f1df75dec12
