### ISSUE TITLE
Interactions need event timestamps

### ISSUE THREAD

**Issue by neuroscr** [appdotnet/api-spec#269]
Getting a list of the last 20 interactions, I'm unclear how recent they are. 

For example, I get a type: 'follow' for my user object with 3 user objects attached in "objects". Each of these 3 user objects should have a timestamp of when this action happened.
Or
the main interaction object could have a first event/last event timestamp. That would also be extremely helpful.

**Comment by ludolphus** [comment]
Hi Ryan, I posted a similar issue here https://github.com/appdotnet/api-spec/issues/247 Also mentioning the timestamp.

**Comment by orianmarx** [comment]
We've added an "event_date" field to interactions. http://developers.app.net/docs/resources/interaction/#interactions-fields
