### ISSUE TITLE
Accessing public stream api

### ISSUE THREAD

**Issue by nanek** [appdotnet/api-spec#27]
I am on the alpha, and I can successfully create an app, authenticate a user to get a user access token and and access the user stream API. However, the public stream request returns 404 (https://alpha-api.app.net/stream/0/streams/public) Does then mean the public stream API is not available yet? 

Or do I need a client access token to access this? If so, what endpoint do pass my client_id/client_secret to? I tried to POST to the public stream resource with my client_id/client_secret with no success.

Not sure where the best place to post this question is. Feel free to redirect me. Thanks! Looking forward to building some apps!

**Comment by kosso** [comment]
The docs need changing (at least for the alpha).

The current 'global' stream is now here  https://alpha-api.app.net/stream/0/posts/stream/global

Dev chat is here : https://www.hipchat.com/garqCaGOZ

**Comment by nanek** [comment]
Thanks! This works. I called that endpoint with an access_token on the querystring.
