### ISSUE TITLE
Add en_US to the supported languages list

### ISSUE THREAD

**Issue by frankieroberto** [appdotnet/api-spec#270]
en_US is missing from the supported languages list at https://github.com/appdotnet/api-spec/wiki/Language-codes

Whilst you might argue than 'en' can be assumed to be 'en_US' at the moment, that might not always be true in the future.

Having locale-specific versions of English specified (British English, American English, Australian English, etc) is useful for spelling and text-to-speech pronunciation libraries.

**Comment by berg** [comment]
In our API, 'en' can always be assumed to be 'en_US.' We support the other sublocales explicitly, e.g. en_GB, en_AU.

**Comment by frankieroberto** [comment]
This is a very US-centric view of the world, no? Why not strive for accuracy and support en_US explicitly?
