### ISSUE TITLE
Unable to log out of Omega

### ISSUE THREAD

**Issue by DaveWoodCom** [appdotnet/api-spec#271]
There's currently a bug on omega.app.net that prevents a user from logging out.

To reproduce:
1. Visit alpha.app.net. Log in.
2. Tap Messages to go to omega.app.net, see that you are logged in.
3. Tap logout. You're redirected to alpha.app.net and logged out.
4. Go to omega.app.net directly.  See you are still logged in.

For step 4, in Safari on Mac, I see the user logged in immediately.  In Chrome on Mac, it did show the user logged out at first, but going to omega.app.net a few times in a row, it did show the user logged back in.

**Comment by orianmarx** [comment]
This has been fixed, thanks.
