### ISSUE TITLE
Stream object_types upgrades

### ISSUE THREAD

**Issue by neuroscr** [appdotnet/api-spec#273]
To change my object_types, I have to shutdown my daemon, delete the old stream and create a new stream. During that time all data in my stream queue is lost when switching to the new stream. Can we get a way to update the object_types without losing our queue (possibly keeping the same stream id).

**Comment by orianmarx** [comment]
You can now update a stream http://developers.app.net/docs/resources/stream/lifecycle/#update-a-stream
