### ISSUE TITLE
User ID is not a string in JSON from the Text Processor

### ISSUE THREAD

**Issue by mattrubin** [appdotnet/api-spec#277]
In all other JSON from the API, user IDs are passed as strings, and the [Entities spec](http://developers.app.net/docs/meta/entities/) specifies that the `id` property in a mention object will be a string. When I @ mention a user in text passed through the [Text Processor](http://developers.app.net/docs/resources/text-processor/), though, the `id` in the mention entity is returned as an (unquoted) number.

From the entities spec:

``` json
"mentions": [
    {
        "name": "berg",
        "id": "2",
        "pos": 0,
        "len": 5,
    }
]
```

From the text processor spec:

``` json
"mentions": [
    {
        "id": 3,
        "len": 10,
        "name": "voidfiles",
        "pos": 22
    }
]
```

This is a fairly trivial inconsistency to handle once discovered, but it can cause trouble when the `id` is assumed to be a string.

**Comment by mthurman** [comment]
Sorry for the inconsistency, it should be fixed now (the docs will be updated shortly)

**Comment by orianmarx** [comment]
Docs are updated.
