### ISSUE TITLE
Filter field for post text/html

### ISSUE THREAD

**Issue by adrianparker** [appdotnet/api-spec#28]
Please can we consider adding a field to the Filter object - allowing a filter to show or block based on post.text containing filter.text (ditto post.html containing filter.html). 
For bonus karma can filter.text or filter.html please allow match by regex? (a nice to have, plain text match would do)

As an app.net member, I never want to see a post that contains text "4sq.com" OR "became mayor of" ever again.

**Comment by markwilcox** [comment]
The filter documentation already includes filters for mention_user_ids and link_domains both of which could be used to filter out all 4sq posts. We also have hashtags in there already - between those it should be possible to filter most/all automated app spam from your stream.  There's not much point in apps spamming if they don't link/direct you anywhere else after all.

I think the regex idea is a nice one in any case. Not sure if it's feasible from a computational cost perspective - that level of filtering might be better implemented in client apps.

**Comment by adrianparker** [comment]
Those fields are somewhat useful for filtering, but definitely don't cover all filtering use cases. I'd like to be able to filter directly on the post.html and/or post.text

Perhaps I want to filter all mentions of "bieber" (I know, who would do that? But as an example ;)  Not just filter #bieber, or posts by @bieber, or posts from bieber.app, or posts that mention beiber.com, but anything bieber. Anything at all. You mention bieber, I don't want to see it. Not even if you post that Bieber has retired.

I agree the existing filter fields are very useful, but I do feel there is a use case for filtering on post content itself, not just post metadata.

Regex is an icing on the cake idea.

**Comment by markwilcox** [comment]
Got any more use cases to justify the extra effort being on the server side. There's a solution to posts that mention "bieber" already, it's called the unfollow button. ;)

After all, there's nothing to stop a client app removing posts from your stream with a RegEx after you've got it from the API.

**Comment by adrianparker** [comment]
Sure we can implement it client side, we could implement all of the Filter spec client side... 

but I think it would be cool to add "string match in post content" filtering to the Filter spec, next to those other things I could do client side, but dont need to because the API is awesome and does it for me...

Doesn't strike me as an unreasonable amount of extra effort to add it. But, hey, its just an idea.

**Comment by markwilcox** [comment]
I don't know anything about the server side architecture but I suspect it's pretty easy to add code to do what you're suggesting. I'm simply thinking about the server load that coud be generated by every user having the contents of every post in their stream searched 20 times to filter for various things they don't want to see. If that's OK with the team then I think it's a great convenience to add it to the API. :)

**Comment by abitgone** [comment]
@markwilcox Adding code to do this feature would be, as you say, pretty easy. Not sure that scaling it to hundreds of thousands of users with multiple filters per user, would be quite so easy though. I'd love it to be part of the API (twitter has given me endless use cases) but I'd be satisfied with client support (as I am with Tweetbot).

**Comment by orianmarx** [comment]
The current Filter capabilities are pretty extensive. http://developers.app.net/docs/resources/filter/

I'm closing this thread but we can reopen it for new suggestions reflecting the current capabilities.
