### ISSUE TITLE
More thumbnail information in post oEmbed annotations based on Files?

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#280]
Right now, if I post a photo via alpha.app.net, the post has an oEmbed annotation for the uploaded File. Yeah!

ADN currently generates two derived files, 200x200 and a larger one. Right now the 200x200 image URL and dimensions are being returned as the thumbnail information in that annotation. That seems like a good baseline, but I'd like to take advantage of the larger derived file as well.

I'm guessing that there isn't a special URL parameter to pass in to expose more data in that annotation, so could the oEmbed annotations created by annotation replacement values  include this other information? (I'm presuming that's Alpha's approach, that's how I checked these annotations out. I'm guessing we'll all use those ... thanks for that by the way!) 

I think I could fire off separate requests based on the provided file_id to get that information from the File API, but those roundtrips can take several seconds for my users and they won't like that very much as they're scrolling on their merry way.

Thanks!

**Comment by mthurman** [comment]
I still have to update the docs, but we just rolled out thumbnail_large\* images if we have an image_thumb_960r derived file (corresponding to the larger thumbnail).

**Comment by tigerbears** [comment]
Right on, thanks! Works like a charm. :)

**Comment by mthurman** [comment]
Alright, the docs are now live: https://github.com/appdotnet/object-metadata/blob/master/annotation-replacement-values/%2Bnet.app.core.file.md#oembed-format
