### ISSUE TITLE
PUT of multipart/form-data breaks HTTP semantics

### ISSUE THREAD

**Issue by icing** [appdotnet/api-spec#281]
Hi there,

while reviewing your new File API (great thing!), I saw that
you make good use of HTTP (DELETE, 507 etc.). However
I found it odd that you require PUT with multipart/form-data
for completing a file.

HTTP semantics has it that PUT on a resource should replace
the resource with the representation sent in the request. The 
resource is expected to have a equivalent, if not bitwise equal,
representation as the request.

What might want to consider in the File API is either a POST with
multipart/form-data against the incomplete file, or a PUT of the 
binary file content. 

See also the lastest HTTP clarifications: http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-5.3.4

Cheers,

Stefan (app.net: icing)

**Comment by berg** [comment]
I think the docs are actually incorrect here -- to update the content of pre-created a file, you actually do PUT with a binary entity body to the /stream/0/files/1234/content resource and send the proper content-type (e.g., image/png). But we also let you send a multipart upload when _creating_ -- e.g., _only_ with POST, for the express purpose of folding both requests into one. So I do think we're doing the right thing here, unless I'm misreading your issue.

If anything we're just being too liberal in what we do accept (but Jon Postel would suggest there's no such thing.)

I'll leave this open so I remember to double-check the docs.

**Comment by brutella** [comment]
@berg I can't find any documentation about the PUT request on the files content. The [file docu](http://developers.app.net/docs/resources/file/lifecycle/#update-a-file) also states that the only keys that can be updated are `annotations`, `name` and `public`.

**Comment by berg** [comment]
Thanks for reminding me to follow up. It's in the docs right here:

http://developers.app.net/docs/resources/file/content/#set-file-content

I'm going to close this issue given that I've confirmed it's in the docs.
