### ISSUE TITLE
developer-designated indexed ids

### ISSUE THREAD

**Issue by hackervera** [appdotnet/api-spec#283]
Right now the id for resources is arbitrarily assigned on resource creation. it would be _really_ nice if, as a developer, i could assign my own global id to my resource so that i could have a convention in my app that knew the names of things.

I think the best way to implement would give a namespace to a developer, so for example i could create a new post with the id tyler.first_post

it would be _really_ handy :)

**Comment by hackervera** [comment]
adding to this from patter channel @troll Maybe, but we could use it like we do annotations. A common scheme could make them universal. Like the dev id could be "review.user_id"

**Comment by berg** [comment]
I understand the use case for this, but unfortunately I don't think we'll be able to accomodate this request. You're welcome to define an annotation for the purpose of creating these tags if you like.
