### ISSUE TITLE
canonical_url on post contains username

### ISSUE THREAD

**Issue by wjlafrance** [appdotnet/api-spec#289]
The canonical_url on a post object obtained through https://alpha-api.app.net/stream/0/users/@wjl/posts is longer than necessary and contains the user's name. For example, for post ID 2828011 the canonical_url is https://alpha.app.net/wjl/post/2828011 whereas http://posts.app.net/2828011 could be used instead.

Since it contains my username, the link may break if I change my username.

**Comment by berg** [comment]
That's correct. (It's one of the reasons why we restrict username changes.)

You're welcome to create your own posts.app.net/1234 links based upon the "id" returned in the post. The `canonical_url` field isn't going to change.
