### ISSUE TITLE
File URLs

### ISSUE THREAD

**Issue by MOApp** [appdotnet/api-spec#293]
https://d36tc8clsz1tk5.cloudfront.net/adn-uf-01/EJ/RZ/9U/EJRZ9UVr3i4eguYdu-H6uypgPRqhZ-qlSirqlMVSczc?response-cache-control=public%2C%20max-age%3D7200%2C%20s-maxage%3D172800&response-content-disposition=inline%3B%20filename%2A%3DUTF-8%27%27image.png&Expires=1360368000&Signature=aPN7vBhpFXeIEAAvCQ1Z1CqINC71CCiaPoh3bh-ErROJ3AmsbybSfX2Vg7E5jlXOh2zXOwauAxY-KsdtEtdujFILhDkVFKk8-znnAHBXTmPIdnD4M3kWAp9i692q9F545nr6HnKW-5~FRcqbma1fCgFAzQX4aKEfPFp6HwGkj88_&Key-Pair-Id=APKAIWNGPWT6YVKFBWJA

This is what I get as URLs for 'uploaded' files - is this a bug or am I doing something wrong?

**Comment by orianmarx** [comment]
That's not a bug, that's what a url for a file hosted on a CDN looks like. What are you trying to do? It would be best if you came into the lounge http://www.hipchat.com/garqCaGOZ or the dev channel http://patter-app.net/room.html?channel=1383 if you need help.
