### ISSUE TITLE
Updating Avatar endpoint

### ISSUE THREAD

**Issue by scruffyfox** [appdotnet/api-spec#296]
Due to the nature of REST and the fact that you're 'updating' your avatar, surely the endpoint should be a PUT rather than POST?

http://developers.app.net/docs/resources/user/profile/#update-a-users-avatar-image

**Comment by orianmarx** [comment]
Technically we're actually creating a new resource when you "update" your avatar so POST makes sense for us in that context. The alternate response is, we're not trying to adhere too strictly to REST :)
