### ISSUE TITLE
AppDotNetPHP

### ISSUE THREAD

**Issue by jdolitsky** [appdotnet/api-spec#30]
Hi all,

I love the App.net project and wanted to contribute in some way. I've just created a sample PHP library with wrapper functions for the unreleased stream API. It is not implementing any sort of OAuth/security measures yet. 

You can find it  here: https://github.com/jdolitsky/AppDotNetPHP

Please use this to inspire your own developer libraries, or help me maintain this one! 

Thanks!

Josh Dolitsky

**Comment by berg** [comment]
Awesome, thanks! I'll add a link from the main docs to this later.

**Comment by jdolitsky** [comment]
Cool! Bryan, I've added you Mark and Alex as collaborators

**Comment by berg** [comment]
Nice! I know that @voidfiles has done some work on a PHP client – perhaps he can contriibute some of it to this project.

**Comment by jdolitsky** [comment]
The library has now been tested with the alpha API and implements OAuth etc. Can you direct me to a list of API calls that are currently live?

**Comment by voidfiles** [comment]
@jdolitsky thanks for creating the PHP lib. We are trying to keep the documentation updated with what works, and what doesn't. That is probably the best place to look.
