### ISSUE TITLE
File list filter by source/client or type.

### ISSUE THREAD

**Issue by kosso** [appdotnet/api-spec#302]
I really wish there was a way to filter the list of my App.net Files by type.  

Or even a filter of the source/client_id which uploaded it. (That would at least create a top level 'App Folder' as we get with DropBox apps without 'full' permissions.)

It would help stop these lists getting unwieldy.

I seem to remember some talk about a 'standard' way to do a pseudo-folder structure.

**Comment by ludolphus** [comment]
There have been talks about folders indeed, read up here: https://github.com/appdotnet/object-metadata/issues/7
No conclusions or solution yet..

**Comment by mthurman** [comment]
Does the `file_types` qs parameter do you what you need? http://developers.app.net/docs/resources/file/#general-parameters

**Comment by kosso** [comment]
ooo.. hadn't seen that.

thanks. that should do it ;)

(In fact the General parameters link do with being linked more visibly in
places in the docs. Quite a few times, I find myself hunting for it)

I still like the idea of a top level 'folder' with the name of the
client_id of the app which uploaded it.

K

**Comment by orianmarx** [comment]
I've put it on my list to link to the general parameters in more places.
