### ISSUE TITLE
X-RateLimit-* headers not being sent in API responses

### ISSUE THREAD

**Issue by briancline** [appdotnet/api-spec#313]
Sent out a few questions about this last night but not sure if anyone has looked into it. Looks like the documented X-RateLimit headers aren't being sent in API responses. This is occurring for both authenticated and unauthenticated requests.

The documentation mentions these headers will be present in responses:

```
X-RateLimit-Remaining: 4959
X-RateLimit-Limit: 5000
X-RateLimit-Reset: 3600
```

However, these are the only headers I'm seeing (this example was a request for `/stream/0/posts/tag/rollout`; I've not yet seen any other calls which include the rate limit headers):

```
Server: nginx/1.2.6
Content-Type: application/json
Content-Length: 2529
Connection: keep-alive
X-ADN-Migrations-Enabled: follow_pagination=1&disable_min_max_id=1&pagination_ids=1&response_envelope=1
Strict-Transport-Security: max-age=86400
Date: Wed, 13 Mar 2013 04:57:19 GMT
Access-Control-Allow-Origin: *
P3P: CP="App.net has no P3P policy."
```

**Comment by mxml-barmstrong** [comment]
You're absolutely right - we introduced a regression that caused us to not send these headers. You should be able to see them again.

**Comment by briancline** [comment]
Excellent, they are indeed showing up again. Thanks for looking into it!
