### ISSUE TITLE
How to update the content of a file?

### ISSUE THREAD

**Issue by brutella** [appdotnet/api-spec#317]
Going through the File API documentation, I couldn't find a way to change the content of a file.

Thanks @berg for [pointing out](https://github.com/appdotnet/api-spec/issues/281#issuecomment-14980398) on how to set the file's content. But that seems to be possible only for incomplete files.

I want to build an app which creates and updates files on ADN - any way to achieve that?

**Comment by orianmarx** [comment]
You cannot update the content of existing completed files right now. You have to create a new file. (You could update an annotation on the existing file to have a pointer to the "updated" version).
