### ISSUE TITLE
Always return a numeric result code in ALL META data (NOT just 200)

### ISSUE THREAD

**Issue by hybotix** [appdotnet/api-spec#334]
If you return a numeric result code in ALL META data, it would be MUCH easier to check for errors and print out the error message. This would be SO useful, and would really help choose actions for API level errors that might not be trappable otherwise.  Sometimes, knowing what type of error occurred can make code and processing more understandable and easier to maintain.

ADN could tell developers much more about what is happening with the API by returning an appropriate numeric result/error code. Let a result code 200 actually mean all is well and go on with normal processing. :)

**Comment by berg** [comment]
Can you help me understand where you're not seeing a numeric result code? Perhaps provide a sample response body and headers?

**Comment by hybotix** [comment]
Yes, I will track this down again and send you the info.

8-Dale

**Comment by berg** [comment]
I'm going to close this - feel free to reopen if you have some examples.
