### ISSUE TITLE
Timed (future) Posts...

### ISSUE THREAD

**Issue by joecarney** [appdotnet/api-spec#34]
Being able to set the exact date and time of a post, before it is sent would would rock.  By making them transparent (i.e. a 'future posts' menu option so you could see who has what pending) you could really turn the network into something else.  

With transparency, you could highlight any marketing spam, and we could have a platform that is both realtime and constantly looking at the future...

**Comment by wedtm** [comment]
Isn't this something that's geared more towards a 3rd-party app's role? Is it really in app.net's scope to provide this?

**Comment by joecarney** [comment]
Depends. If the API allows you to set the post date/time.  Why build 3rd party apps if you can post with a future date and time?

**Comment by wedtm** [comment]
Hrm, that's a good point. I guess that would all depend on what Dalton &
Co.'s scope definition looks like :)

**Comment by Burnsoft** [comment]
bufferapp.com recently added the ability to post to appdotnet.
I use them a lot for scheduled Tweets.
Their free account allows 10 messages to be buffered. (if you use this code I think we both get an additional one - http://bufferapp.com/r/178f6)
ALso, tweet4me.com is a service that easily schedules tweets using any twitter client. I'd expect them to add ADN soon also.
Hope this helps.

Cheers
Nik

**Comment by joecarney** [comment]
I use bufferapp, great service, but was thinking of something different. With transparent future dates this service could offer a whole lot more :)  

Joe

**Comment by mthurman** [comment]
I agree with @wedtm and @Burnsoft right now--this seems like the perfect use case for a 3rd party adding value (especially since people like Buffer have already written it). I'm going to close this issue.

If you have a strong use case for why it should belong in the core api instead of a 3rd party app, please reopen.
