### ISSUE TITLE
Sending a message to a channel shouldn't flip the "unread messages" bit if there were no unread messages

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#340]
I get that unread/read in a channel is driven by stream marker at some level, but it would be great if sending your own messages to a channel didn't mark the channel as dirty (but didn't overwrite the current stream marker).

**Comment by mthurman** [comment]
Is there a reason you can't send an "update stream marker" api call once you have the message id? That's what Omega does and it seems to work pretty well.

We want to make pm type applications really easy to make on top of channels, but we're also hesitant to make channels to tied to pm style applications (or special case them more than they already are).

We can definitely imagine non-pm situations where that behavior wouldn't be desired so I think making a 2nd API call is the best way to resolve this. I'm going to close this issue, but if you don't think that's a suitable resolution, feel free to reopen.
