### ISSUE TITLE
oembed annotations: thumbnail_width and _height values may be incorrect

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#342]
For this post: https://alpha-api.app.net/stream/0/posts/7095753?include_annotations=1

the thumbnail width/height values are 200 and 200. However, the dimensions of the image at the thumbnail_url are 640x360. That post is a quoted repost of the following post; its annotation's large thumbnail dimensions are indeed 640x360.

 https://alpha-api.app.net/stream/0/posts/7095210?include_annotations=1

**Comment by mthurman** [comment]
The annotation for 7095753 was not generated by the App.net API (it has no file_token_read or file_id). That oembed data was provided by a client when the post was created. You may want to reach out the the riposte guys to report this.
