### ISSUE TITLE
No 'data' for App-Stream 'user_follow' delete.

### ISSUE THREAD

**Issue by appox** [appdotnet/api-spec#346]
Here is a example of an app-stream json entry without 'data':

> {"meta": {"timestamp": 1375305209609, "is_deleted": true, "type": "user_follow", "id": "2301417"}}

It not happens all the time. (41 out of 1320 times in the last 10h)

**Comment by berg** [comment]
I believe this happens when a user account is being deleted. You can safely ignore these.

**Comment by appox** [comment]
Works for me :-)
Thanks.
