### ISSUE TITLE
Modifying annotations on an existing file doesn't seem to trigger a user stream event

### ISSUE THREAD

**Issue by peteburtis** [appdotnet/api-spec#349]
PUTing an update to an existing file that sets new annotations doesn't seem to trigger anything on a user stream subscribed to file storage.

Renaming a file and/or toggling the public/private setting both behave as expected, causing an updated version of the file to be pushed down the stream.

Modifying the file's name or public/private setting **and** changing the annotations in the same PUT request also behaves as expected, sending down a file object with the new, updated annotations.

**Comment by mthurman** [comment]
Sorry about that, this should be fixed now.
