### ISSUE TITLE
Counts wrong in basic profile info

### ISSUE THREAD

**Issue by jschlesser** [appdotnet/api-spec#35]
I have a client token that is authenticated with stream only.    When I view my profile the counts are all zero and they are non zero on alpha.app.net (as they should be).   user @josh.

URL
https://alpha-api.app.net/stream/0/users/me?access_token=...

Results
{
    "app_data": null,
    "avatar_image": {
        "height": "200",
        "url": "https://d1f0fplrc06slp.cloudfront.net/assets/user/5d/50/00/5d50000000000000.jpg",
        "width": "200"
    },
    "counts": {
        "followed_by": "0",
        "follows": "0",
        "posts": "0"
    },
    "cover_image": {
        "height": "230",
        "url": "https://d1f0fplrc06slp.cloudfront.net/assets/user/fe/50/00/fe50000000000000.jpg",
        "width": "960"
    },
    "created_at": "2012-08-08T01:09:05Z",
    "description": {
        "entities": {
            "hashtags": [],
            "links": [],
            "mentions": []
        },
        "html": "<span itemscope=\"https://app.net/schemas/Post\">Levity is the cosmological constant.</span>",
        "text": "Levity is the cosmological constant."
    },
    "id": "390",
    "locale": "en_US",
    "name": "Josh schlesser",
    "timezone": "America/Los_Angeles",
    "type": "human",
    "username": "josh"
}

**Comment by tgvashworth** [comment]
I've noticed the same issue, all my counts are 0.

**Comment by ralfr** [comment]
Same here. I also noticed we cannot assign labels here on GitHub. @berg?

**Comment by mthurman** [comment]
This was fixed today

**Comment by jschlesser** [comment]
Yay, thanks @mthurman
