### ISSUE TITLE
Post Search docs mentions seemingly non-functional has_location parameter

### ISSUE THREAD

**Issue by rrbrambley** [appdotnet/api-spec#356]
From the [docs](http://developers.app.net/docs/resources/post/search/#search-for-posts): 

> has_location  Optional    int (0 or 1)    Only include posts containing geo coordinates, i.e., tagged with the net.app.core.location annotation

I've tried a bunch of queries with this parameter and I can never get any posts to be returned. Furthermore, I cannot find any documentation on the net.app.core.location annotation.

I was guessing that this might have been a typo and that the param is actually has_geolocation, but that doesn't seem to work either. So perhaps your server recognizes has_location, and then literally does look for that net.app.core.location annotation, which always yields 0 results because no such annotation exists on any posts?

**Comment by cdn** [comment]
Isn’t the annotation actually geolocation? [docs](https://github.com/appdotnet/object-metadata/blob/master/annotations/net.app.core.geolocation.md)

**Comment by rrbrambley** [comment]
@cdn that is _an_ annotation, and that's exactly what I was alluding to – they might not be returning search results for the correct annotation.

**Comment by mdornseif** [comment]
As a workaround `/stream/0/posts/search?include_annotations=1&annotation_types=net.app.core.geolocation` works while `/stream/0/posts/search?include_annotations=1&has_location=1` fails by returning no posts at all.

**Comment by mxml-barmstrong** [comment]
Thanks for pointing this one out. We've rolled out a fix for it.

**Comment by rrbrambley** [comment]
@mxml-barmstrong The docs still reference a net.app.core.location annotation.

**Comment by mxml-barmstrong** [comment]
Oh, oops, that is supposed to say net.app.core.geolocation.
