### ISSUE TITLE
Dead link on the Messaging Basics page

### ISSUE THREAD

**Issue by bryanjclark** [appdotnet/api-spec#360]
On this page:
http://developers.app.net/docs/basics/messaging/

Under the heading "Subscriptions", if I click the link "subscription preferences", I get a 404 page at this URL:
https://account.app.net/settings/messaging-permissions/

Any chance the page still exists?

**Comment by mthurman** [comment]
I just pushed a new version of the docs that has an updated link: https://account.app.net/settings/privacy/#messaging
