### ISSUE TITLE
Bug in Interactions endpoint pagination when using interaction_actions without "reply"

### ISSUE THREAD

**Issue by HaiColon** [appdotnet/api-spec#368]
I think I've found a bug in the Interactions endpoint.

When I request the following URL:

```
https://alpha-api.app.net/stream/0/users/me/interactions?interaction_actions=follow,repost,star&count=20
```

It returns as meta.max_id: 7203027

When I then request the URL:

```
https://alpha-api.app.net/stream/0/users/me/interactions?interaction_actions=follow,repost,star&count=-99&since_id=7203027
```

It returns one new "follow" event and a new max_id even though it should return nothing new since nothing new happened. This happens four times, then it stops. Each time the follow action has less users in the users field, but all of them have already been shown in an earlier event so they shouldn't be displayed again. It seems to only happen if I leave out the "reply" action, if I leave out "star" or "repost" everything seems to work fine.

The URLs/IDs used here are from my ADN account cauldron, but it also happens with my other account chriscolon. Same thing, but there it stops after three times instead of four which I guess depends on how many users where in the follow event that keeps getting displayed.

**Comment by mthurman** [comment]
Yeah, that's definitely a bug. I'll work on getting a fix out today.

**Comment by HaiColon** [comment]
Awesome, thanks! :)

**Comment by mthurman** [comment]
Ok @HaiColon I think that should be fixed now. Please let me know if you still see this issue.

**Comment by HaiColon** [comment]
@mthurman This specific issue is fixed, but I'm afraid there seems to be another problem with it now. If I leave out the "reply" and just request "follow,repost,star", the follows from the last couple of days are missing. If I add "reply" they are there again. Other combinations seem to work fine.

**Comment by mthurman** [comment]
I followed up with @HaiColon and this was related to the more "dynamic" nature of the Interactions stream. All of the data was still there, just in later pages.
