### ISSUE TITLE
include_inactive ignored by https://api.app.net/channels?ids=…

### ISSUE THREAD

**Issue by tonyarnold** [appdotnet/api-spec#375]
When I specify the ID of channels that have been made inactive, even if I add `include_inactive=1` in my query string the inactive channels are never returned. 

For example: `https://api.app.net/channels/?ids=49330&include_inactive=1` returns:

```
HTTP/1.1 200 OK
Server: nginx/1.4.7
Content-Type: application/json
Content-Length: 31
Connection: close
X-RateLimit-Remaining: 4678
X-ADN-Migrations-Enabled: include_new_interactions=1
Strict-Transport-Security: max-age=31536000
X-RateLimit-Limit: 5000
ETag: g7QjJSEzVyXCXgRuyoOAbWmI0CQ
Date: Mon, 14 Apr 2014 04:25:51 GMT
X-OAuth-Scopes: files,update_profile,messages,stream,basic
Access-Control-Allow-Origin: *
X-RateLimit-Reset: 572
P3P: CP="App.net has no P3P policy."

{"meta":{"code":200},"data":[]}
```

Requesting them individually via `https://api.app.net/channels/49330?include_inactive=1` works fine.

**Comment by mthurman** [comment]
A fix for this has been rolled out. Thanks for the bug report!

**Comment by tonyarnold** [comment]
:thumbsup: :boom: Thanks guys, incredibly speedy fix!
