### ISSUE TITLE
User streaming - Add post hashtag search

### ISSUE THREAD

**Issue by neuroscr** [appdotnet/api-spec#377]
Applications like Vidcast could really use a hashtag filter on user streaming, so that clients can easily listen on a hashtag without having to poll your service.

Could also just implement posts/search functionality in user stream, that would be more powerful and useful. but of course, I prefer what ever you can get going faster to start =]

**Comment by mthurman** [comment]
Ok, this is now possible. Let me know if you run into any issues.
