### ISSUE TITLE
<null> Post Bodies

### ISSUE THREAD

**Issue by harry-isaac** [appdotnet/api-spec#38]
When I download my stream from the API to my iOS client on one post all the post values are null: 
{
    annotations =     {
    };
    "created_at" = "2012-08-11T06:44:59Z";
    deleted = 1;
    entities =     {
        hashtags =         (
        );
        links =         (
        );
        mentions =         (
        );
    };
    html = "<null>";
    id = 21115;
    "reply_to" = 21101;
    source =     {
        link = "<null>";
        name = "<null>";
    };
    text = "<null>";
    user =     {
        "app_data" = "<null>";
        "avatar_image" =         {
            height = 200;
            url = "https://d1f0fplrc06slp.cloudfront.net/assets/user/0a/e0/00/0ae0000000000000.jpg";
            width = 200;
        };
        counts =         {
            "followed_by" = 0;
            follows = 0;
            posts = 0;
        };
        "cover_image" =         {
            height = 1707;
            url = "https://d1f0fplrc06slp.cloudfront.net/assets/user/79/e0/00/79e0000000000000.jpg";
            width = 1280;
        };
        "created_at" = "2012-08-10T01:08:16Z";
        description =         {
            entities =             {
                hashtags =                 (
                );
                links =                 (
                );
                mentions =                 (
                );
            };
            html = "<span itemscope=\"https://app.net/schemas/Post\">I am a network researcher working on ProtoGENI and Emulab. In my spare time I sometimes make flash games like \"Tile Factory\" and \"Shattered Colony: The Survivors\". I am interested in making an actual social game (as opposed to nagware like Zynga).</span>";
            text = "I am a network researcher working on ProtoGENI and Emulab. In my spare time I sometimes make flash games like \"Tile Factory\" and \"Shattered Colony: The Survivors\". I am interested in making an actual social game (as opposed to nagware like Zynga).";
        };
        id = 1268;
        locale = "en_US";
        name = "Jonathon Duerig";
        timezone = "America/Los_Angeles";
        type = human;
        username = duerig;
    };
}

This is only happening for this one post.

**Comment by harry-isaac** [comment]
I'm not used to GitHub yet, they took out the "<null>"'s. In text and html there were "<null>"'s.

**Comment by ozetadev** [comment]
I have this problem too. When someone posts something new with a blank text value, it still goes through, and causes issues on the API side (not the site side)

**Comment by voidfiles** [comment]
Null post bodies occur when a user has deleted a post. You can tell because it says deleted: 1. We remove the content completely from our database. The reason that it's still around though is that it could be apart of a conversation, and we don't want to break that chain so we need to leave a tombstone of it around. 

We decided that it should be up the clients how they want to display deleted posts. You could choose to not display them at all if you wish.
