### ISSUE TITLE
Adding basic concept of public vs. private (limited view) posts

### ISSUE THREAD

**Issue by rgerard** [appdotnet/api-spec#4]
While I'm not trying to open up the can of worms that is the permissions model discussion, I do think it would make sense to have some rudimentary idea of posts that are public, vs posts that are private or limited in viewing scope.   I would add something like the following to the Post object:

For public posts:
"viewable": "all",

For private/limited posts:
"viewable": "@berg, @dreadpirateryan, @daltonc",

**Comment by berg** [comment]
This is something we intend to address. We want to make the controls regarding which applications and users are able to see a user's posts relatively granular, and we intend to allow for private messages.

Obviously posts which weren't visible wouldn't show up to users who couldn't see them—just to be sure, it seems like this would be an advisory attribute which would allow clients to surface the privacy of a given post to users, right?

**Comment by rgerard** [comment]
I was actually thinking about this attribute in the terms of post submission -- when a client submits a post to the service, this attribute would be used to mark who the user thinks should see it.  The backend service could then use this attribute to help determine which feed has access to this post.

As to sending this attribute to clients, I'm not certain it's necessary to reveal all the information, esp in the case of a private post.  When sending a post to a client, if it's a private/limited post, I imagine it would be best to mark the attribute as something like this:

 "viewable": "limited",

or 

 "viewable": "direct",

That way, the client can markup the UI appropriately to indicate to the user somehow that this was a "limited view" post, or a direct message.

**Comment by rykorp** [comment]
I, too, would like to see some level of permission granularity introduced to objects - I'm trying to escape posting personal items to the AdSocNets, and being able to control that would be fantastic. At the most basic level it could be as simple ad public, limited audience (those who I've put into a friends list?), and private (which I guess would simple be an exclusion of all users except self). 

I'm guessing permission might be a bit initial lift - pure public would probably function fine in a v1, although the reason for the draw of projects like Diaspora shouldn't be ignored.

**Comment by datariot** [comment]
I would love a Unix style user/group privacy model on posts. This would allow for an 3rd party implementation like G+ circles, business applications where group privacy is important, or just plain DM.

**Comment by orianmarx** [comment]
I'm closing this thread as we've introduced the Messaging API: http://developers.app.net/docs/basics/messaging/
