### ISSUE TITLE
Prefer the min_id to not be inclusive of the specified id

### ISSUE THREAD

**Issue by prasadrl** [appdotnet/api-spec#40]
api - /stream/0/posts

When clients request for posts since min_id, the response contains the post _with_ min_id. Clients now have to specifically remove this post from the response before displaying the response. To avoid this, if the min_id is passed as last_returned_id+1, the response for some reason includes the entire list of posts. Is this a bug ? 

IMO, I would prefer that the response did not include the post with min_id.

**Comment by wedtm** [comment]
By the very name "min_id" you are specifying the MINIMUM ID of the object you wish to receive. It would seem painfully obvious that if you don't want the record that's included with "min_id" you'd simply call for min_id + 1. Certainly this makes  sense, right?

**Comment by dquick-freelance** [comment]
@wedtm It would, except that the API specifies that IDs are strings, not ints.  So while the current datastore certainly seems to be amenable to min_id + 1, I'm not sure as developers we can count on that always being the case.

**Comment by wedtm** [comment]
I completely agree, I think the same would still hold true though, that a
call with a parameter for "min_id" should return results including the
record stated within the "min_id" parameter.

**Comment by prasadrl** [comment]
This is now fixed with since_id parameter. Thanks!
