### ISSUE TITLE
Replace a property “indices” with a more intuitive name “range”

### ISSUE THREAD

**Issue by shpakovski** [appdotnet/api-spec#41]
Some objects returned by current API have a property named `indices`, i.e. [Mentions](https://github.com/appdotnet/api-spec/blob/master/objects.md#mentions). However, the format of this property is not as readable as it could be if we used an idea of range.

For example, an equivalent to `"indices":  [34, 42]` would be `"range": [34, 8]`. I believe this is a better way to recognize a substring within a piece of text. Makes sense?

**Comment by eschaton** [comment]
Indices also implies, at least to Cocoa developers (who spell it "indexes"), that discontinuities are allowed. E.g. `indices: [34, 42]` looks to some of us like "index 34 and index 42," not "indices 34 through 42 (inclusive)."

**Comment by mthurman** [comment]
This has been changed to be "pos" and "len" indicating the starting position and length of entity: http://developers.app.net/docs/meta/entities/
