### ISSUE TITLE
Increase precision of post creation timestamps

### ISSUE THREAD

**Issue by tigerbears** [appdotnet/api-spec#46]
The precision of the creation date timestamp for posts is currently one second. Posts on the global feed will soon start coming in at several (many) per second. Having timestamps that include fractions of a second will soon be important for clients that need to re-sort posts by creation time.

**Comment by mthurman** [comment]
We want timestamps to be used in UIs, not for sorting. Thus I don't think subsecond precision is necessary. The docs have been updated to reflect that ids can be assumed to be integers (https://github.com/appdotnet/api-spec/blob/master/objects.md#object-ids) and these ids should be used for the sort order of posts (https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#sorting-posts).

**Comment by tigerbears** [comment]
Just saw that update - solves the sorting thing nicely. Thanks!
