### ISSUE TITLE
"OAuth error. Sorry :("

### ISSUE THREAD

**Issue by harry-isaac** [appdotnet/api-spec#49]
When sending a user to the OAuth page I get "OAuth error. Sorry :(" I have tried replacing my Client ID with AppApp's client ID since that is public and it works fine. This seems to be only with my Client ID and then I created a new App on the App.net website and used that Client ID and that still didn't work.

**Comment by dopiaza** [comment]
I've seen this message a lot today. Each time it's been because I failed to set my redirect URI correctly. Have you checked that?

**Comment by harry-isaac** [comment]
Yea, I don't think t's  a format issue because if I interchange my client ID it works.

**Comment by harry-isaac** [comment]
Never mind, you were right. It was a URL redirect issue.
