### ISSUE TITLE
HEAD request to posts api to check for new content cheaply.

### ISSUE THREAD

**Issue by KirinDave** [appdotnet/api-spec#50]
One of the most annoying parts of mobile apps for sharing services is the often-awkward "refresh delay" before new content is displayed. In the case of most twitter apps, the developers of said apps have abrogated the decision of when to refresh quickly to the user. API vendors have encouraged this behavior because stream connections are relatively expensive (for a power-constrained client and the servers).

But a better API would give us a very inexpensive (for both client and server) way to ask, "Is there new activity I should be interested in?" and also give an idea of the frequency of said updates for adaptive frequency checks. Backgrounded mobile apps may stick to long polls (for power efficiency) and desktop services may just use a streaming api, but foregrounded mobile apps are left out in the cold in this approach.

An easy way to do this would be to support both Etags and HEAD method requests on the posts API, which currently seems to be omitted from the spec. Lightweight apps could use this to avoid excessive network traffic while still keeping a sub-5-second response time on new content to the user.

**Comment by dch** [comment]
The CouchDB _changes feed is the definitive ideal approach for me. Provide
a sequence number, client simply asks "is there anything new since #seq",
and then waits on either a heartbeat, termination, or a response. The
server doesn't need to keep state then either, but you do need to think
about node ordering within clusters.

**Comment by orianmarx** [comment]
The "meta" field of our response objects should contain sufficient information now to satisfy this. For more info look at http://developers.app.net/docs/basics/responses/. Closing this thread.
