### ISSUE TITLE
Deleted posts still show up in timeline

### ISSUE THREAD

**Issue by mweisman** [appdotnet/api-spec#52]
After deleting a post (37025 for example), it still shows up in my timeline with several of the fields (html, text, entities) having null values. Shouldn't the post be removed from my timeline if I delete it?

**Comment by edent** [comment]
As a user (and developer) I would prefer that the reference stayed intact - even if the contents are deleted.
Otherwise, an "in reply to" link could 404.

**Comment by mweisman** [comment]
Sure, I could see keeping the post object itself around to avoid 404s, but including it in timelines means apps need to specifically work around null text posts to avoid showing them in timeline views. I initially saw this issue in [AppApp](https://github.com/sneakyness/AppApp) which listed a post with the text "null" in my timeline.

**Comment by rgerard** [comment]
There should be a "deleted":1 value returned in the post once it's deleted. I agree that it would be nice if it wasn't returned at all, but checking for the "deleted" value in the post is an easy check.

**Comment by mthurman** [comment]
We've renamed `deleted` to `is_deleted` and it's now a boolean `true`. Right now, we return deleted posts so users can see that pieces might be missing in a conversation. We might add a flag to filter out deleted posts on the server side if apps don't want that data. But we think it's important to have that information available (especially for thread/post detail type views) to maintain some integrity/flow to conversations even as post may be deleted.

https://github.com/appdotnet/api-spec/blob/master/objects.md#post-fields

**Comment by abitgone** [comment]
I like that the deleted 'ghosts' are there. There's nothing more frustrating than following a twitter conversation thread that gets chopped off halfway through because someone deleted a tweet. Maintaining thread integrity alone is worth keeping this there.

**Comment by mthurman** [comment]
We've added this flag (`include_deleted`) https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#general-parameters so I'm closing this issue
