### ISSUE TITLE
Add a property like “has_replies” to the object “Post”

### ISSUE THREAD

**Issue by shpakovski** [appdotnet/api-spec#54]
An object [Post](https://github.com/appdotnet/api-spec/blob/master/objects.md#post) has got a property `"reply_to": null`. This property is great because a client app can optionally show the link “In reply to” in the timeline.

However, if we have this kind of information available at hand, it would be great to also show in the timeline when someone has already replied to the post. For example, the `Post` object would have the property `"has_replies": true`. Makes sense?

**Comment by edent** [comment]
My personal preference would be to have this as a search property "Show me all replies to id 12345".
Or, create a new object called "conversation" which would be a graph of a replies to a post.  Conversations aren't just linear.

**Comment by shpakovski** [comment]
@edent The property `"has_replies": true` (or `"belongs_to_conversation": true`) would help to display some kind of badge on the post which has a conversation attached _right in the timeline_ without diving into the Post screen. And in case of `“show all replies to <id>”` you would need to make as many API requests as many posts in the timeline to achieve the same effect.

I really miss that kind of badge in Twitter apps. Because when you see a “question tweet” it is very interesting if someone has already made an “answer reply”, but you have to dive into the Tweet screen to check if there is anything useful.

**Comment by mthurman** [comment]
Done! We now have `num_replies` which counts the number of direct replies to the given post. (updates to the docs pending)
