### ISSUE TITLE
Email address no longer available on user object?

### ISSUE THREAD

**Issue by ralfr** [appdotnet/api-spec#55]
I just noticed that the user object does not include the email address anymore. Though when requesting scope "email" the Oauth dialog still indicates the requested permission. Is this broken or by design?

**Comment by ralfr** [comment]
Any response?

**Comment by ghost** [comment]
Probably trying to head off privacy concerns? Or legal? Email is serious stuff to people. Both Twitter and FB don't give you the email. In theory I could go I and harvested out 3500 valuable emails otherwise. Not that I would.

**Comment by abraham** [comment]
Facebook gives apps access to users email address.

**Comment by mthurman** [comment]
So far, emails have not yet been exposed through the api. Eventually they will be exposed under the extra `email` scope.

**Comment by mthurman** [comment]
Also just to be clear, `email` will not be on every user object. It will only be on the user object for the user who belongs to the access token that is being used that has the extra `email` scope.

**Comment by ralfr** [comment]
Makes absolute sense. It has to have a dedicated scope but in terms of using App.net as a "login provider", it will be essential. So I'd love to see it higher prioritized (the extra scope and the feature).

**Comment by mko** [comment]
I was about to ask the same question. I definitely am looking to use App.net with the `email` scope and get the user's email address on the `users/me` endpoint.

**Comment by minus88** [comment]
There seems to be "Email" scope now, but still I am not receiving the Email in the user object, is there a seperate URL i would have to call to get the email.

https://alpha.app.net/vignesh

**Comment by mthurman** [comment]
You can request the `email` scope (and authorize it), but right now, we're omitting the email address in responses regardless of the presence of the scope.

**Comment by jaredcwhite** [comment]
Any update on this? I'm considering adding App.net-based account authorization to my web publishing platform (@mariposta on ADN) and it wouldn't really make sense if I had to request the user's email address again separately. I should be able to get it from their ADN user data if they've authorized it.

**Comment by orianmarx** [comment]
There is no change on this yet. I'll follow up when we have a timeframe for getting this rolled out.

**Comment by jaredcwhite** [comment]
Thanks Orian. I would suggest this is even more desirable now with the private messaging API because private group services are more likely to want to send e-mail notifications or other things by e-mail related to the group (perhaps message digests). So automatically retrieving an authorized user's email address would be ideal.

**Comment by matthewl** [comment]
Any update on this @mthurman? I've tried adding an email scope to my authorisation post but I'm still not getting an email address back in the response.

**Comment by mthurman** [comment]
@matthewl Sorry that this was still hanging around, I thought we had closed this issue when we removed `email` from the [scopes list](http://developers.app.net/docs/authentication/#scopes). We've decided that App.net will not be providing email addresses of users through the API. If that is information you need for you app, we recommend asking the user directly for it.
