### ISSUE TITLE
Users complete name should be available for dedicated scope

### ISSUE THREAD

**Issue by ralfr** [appdotnet/api-spec#57]
My little experiment at www.ibackedappdotnet.com raised a [users concern](https://alpha.app.net/jcsnl/post/42846) about the full name being available even if only the basic scope is requested.

We might really have to think about way more fine grained scopes.

**Comment by abraham** [comment]
I don't think name should be any more restricted than username. If users don't want their full name public they should only use their first/handle. Hopefully the App.net web will let users edit it as desired soon.

**Comment by bsag** [comment]
It certainly needs to be clearer what is exposed publicly in the API and what is private. You need the full (real) name for credit card billing, but many users don't want that showing up in the API.

**Comment by orianmarx** [comment]
The data you supply for your account billing is separate from the data you supply for your user profile, and we will not expose your billing info through the API. We also don't require you to use your real name in your user profile. For further clarification I would suggest reviewing the Terms of Service: https://account.app.net/legal/terms/

Closing this thread.
