### ISSUE TITLE
Headless peeps?

### ISSUE THREAD

**Issue by aral** [appdotnet/api-spec#60]
Can appy support headless peeps? In other words, peeps (well, I’m not going to call them tweets here, am I?) with no text, just annotations (metadata). These could be easily filtered from textual timelines and yet prove very useful for other types of messages.

**Comment by fields** [comment]
I think this is covered under https://github.com/appdotnet/api-spec/issues/20

**Comment by tgvashworth** [comment]
Worth referencing #20

**Comment by orianmarx** [comment]
Closing this as it has been implemented as "machine only posts" http://developers.app.net/docs/resources/post/#machine-only-posts
