### ISSUE TITLE
Mentions list returns empty if you use 'min_id' on a deleted post

### ISSUE THREAD

**Issue by johnsheehan** [appdotnet/api-spec#61]
If you specify min_id when calling /users/me/mentions for a post that has been deleted the response is empty. Picking one before or after the deleted posts returns the correct entries.

**Comment by berg** [comment]
Yes, this is something we're working on. Gotta fix ordering in some of our internal data structures. I anticipate we'll have a patch out for this today.

**Comment by mthurman** [comment]
Those underlying fixes went out yesterday (8/14) morning. This should be fixed now.
