### ISSUE TITLE
Follow/Unfollow returns 403 status code

### ISSUE THREAD

**Issue by domness** [appdotnet/api-spec#62]
I'm developing an iOS app for App.net and everything works except for trying to follow/unfollow a user.

I keep getting 403 status codes, when adding an authorization header I then just get 401 status codes?

**Comment by ralfr** [comment]
I noticed this to occur if you did not request the explicit follow scope during OAuth handshake.

## 

Ralf Rottmann | CTO

e: ralf.rottmann@grandcentrix.net
p: +49 221 677 860 20 

On 14.08.2012, at 02:15, Dominic Wroblewski notifications@github.com wrote:

> I'm developing an iOS app for App.net and everything works except for trying to follow/unfollow a user.
> 
> I keep getting 403 status codes, when adding an authorization header I then just get 401 status codes?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

_Wir sind umgezogen – neue Anschrift!_

grandcentrix GmbH
Schanzenstrasse 6-20
51063 Köln, Deutschland

phone: +49 221 677 860 0
fax:    +49 221 677 860 99

Amtsgericht Köln | HRB  70119 | Geschäftsführer: R. Freygang, R. Rottmann, M. 
Willnow | USt.-IdNr.: DE266333969

Werden Sie unser Fan auf Facebook: http://www.facebook.com/grandcentrix

**Comment by domness** [comment]
Hmm, it looks all fine to me, can you elaborate?

**Comment by ralfr** [comment]
Did you make sure you requested the follow scope initially? I ran into the same issue when I tested with an account that initially did not grant the follow scope. Somehow re-authentication with a broader scope seemed to have failed / not propagated.

**Comment by domness** [comment]
Yeh, it was the scopes on authentication
