### ISSUE TITLE
Need a thread ID per post

### ISSUE THREAD

**Issue by coccyx** [appdotnet/api-spec#65]
Would be nice if in addition to reply_to, each post also carried a thread_id which contained the id of the first post in the thread so that all posts in a thread could be easily identified from the data sent with the post.  thanks, @clint

**Comment by abitgone** [comment]
Including the root post's `post_id` as something like `root_post_id`instead would save having to traverse the thread when looking for previous and follow-up posts in the conversation.

**Comment by mthurman** [comment]
The docs have yet to be updated, but we now have `thread_id` for this purpose. Note: this doesn't guarantee there are replies in this thread--see #54.
