### ISSUE TITLE
Need a way to get the user_id of the authenticated user

### ISSUE THREAD

**Issue by rgerard** [appdotnet/api-spec#66]
I hope this turns out to be an already solved problem, and not a real issue.  I'm currently working on an iOS app that is hitting the API.  I have the app successfully authenticating, using the client-side flow.  An access token is being returned successully.

I can use the access token to get the global stream of posts, and get the personalized stream of posts.  However, to get user info, the API is of the format: /stream/0/users/[user_id]

I want to be able to get the user information of the authenticated user that is using my app. Presumably, that means I need the user_id of the logged-in user.  How do I get the user_id for the logged-in user, when I currently only have the access_token?  I don't see an API call for: "here's my access token, please tell me which user this token is associated with".

**Comment by JoshBlake** [comment]
@rgerard /stream/0/users/me
Per https://github.com/appdotnet/api-spec/blob/master/resources/users.md the parameter description.

**Comment by rgerard** [comment]
Ahhh excellent.  Thanks Josh.
