### ISSUE TITLE
Avatar Image Type

### ISSUE THREAD

**Issue by jpittman** [appdotnet/api-spec#67]
Currently on the avatar image object associated with the user object, you have the following:

```
    "avatar_image": {
        "height": 512,
        "width": 512,
        "url": "https://example.com/avatar_image.jpg"
    }
```

Can we get a type key with a string as it's value indicating the type of image it is?   Like so:

```
    "avatar_image": {
        "height": 512,
        "width": 512,
        "type": "jpg"
        "url": "https://example.com/avatar_image.jpg"
    }
```

**Comment by ralfr** [comment]
I'd suggest if that gets added, we make use of standard mime types as defined here: http://www.iana.org/assignments/media-types/index.html.

**Comment by orianmarx** [comment]
Since the url for an image can potentially contain a query string, our suggestion is to look at the MIME type of the response from the url. Also using annotations should go a long way to resolving this. Closing this thread.

**Comment by mattflaschen** [comment]
@orianmarx, why would it contain a query string?  This is referring to the built-in avatar image, which seems to always use CloudFront with no query string or extension.

That said, CloudFront is serving the mime type header in my tests, so that will work.

**Comment by orianmarx** [comment]
Yeah sorry, I was conflating this with something else that wasn't specifically referencing avatars. Either way, yeah you should get the MIME type in the response so we're not going to make any change here. Thanks for catching that.
