### ISSUE TITLE
Including the scopes granted in user object

### ISSUE THREAD

**Issue by ralfr** [appdotnet/api-spec#68]
May I suggest that the granted scopes will be returned to an app when requesting the user object. Or a link to the currently valid scopes resource. That way, when an app needs to expand (or reduce) scopes, it can handle the process more intelligently from a usability standpoint as just trying some action and running into a scope issue.

**Comment by simondlr** [comment]
I second this.

**Comment by mthurman** [comment]
Still working on updating some docs, but we now have `GET /stream/0/token` that returns some useful information about the current OAuth Token. Also, don't forget about the `X-OAuth-Scopes` header https://github.com/appdotnet/api-spec/blob/master/auth.md#scopes

**Comment by ralfr** [comment]
Question: When I redirect an already authenticated user to the OAuth endpoint requesting a different (less or more) scope than currently authorized, will App.net recognize and show an updated dialog?

**Comment by mxml-barmstrong** [comment]
Update on two points on this one
1. GET /stream/0/token is hooked up. Have a look at what's in 'scopes'.
2. Yes, the dialog shows which scopes currently exist and which are being newly requested. It doesn't yet show less scopes but that's because there's no dialog that will activate for that case.
