### ISSUE TITLE
SPAM starting filters needed, Filters Comments from @josh

### ISSUE THREAD

**Issue by jschlesser** [appdotnet/api-spec#69]
First, we are starting to see a teeny bit of stuff that looks spammy.  Filters would be nifty to have now, specifically the user level filter but read below about my concerns with filters for spam and per user instances.

I think one of the most common uses will be to block unwanted spammy content from a users stream, not in a specific client or specific stream but as a kind of prefilter on all that users streams.   Its likely that there will be a use case for 3rd party maintained large global block lists.  You probably dont want those being copied all over the place into every users account.   Its likely they will be very large in terms of the number of filtered elements.  It would be more efficient to have a way to kind of subscribe to a particular filter to route a stream through it so to speak so that maybe only 1 need exist and some party (app or something) can be responsible for maintaining the ids etc... and they can design the algorithm, X trusted people block, that id goes onto the list.

If Alpha is going to be a going concern then a way for people to build plugins with UI elements will be needed there as well so that users can do things like subscribe to a blocking service and the block button will show up in that users UI.  The alternative is that we have browser windows open for every little thing we want. 

I think that there is also a case to be made for people sharing filters and chains of filters as more of a curation system to support particular views of information.   It might be that a users view of the global stream gets filtered through their big global block lists for spam etc... then through a personal block list or whitelist and then potentially through some sort of curation system where the intent is more to hone an maintain various contexts.

There may also be a case for push filters where it acts as a kind of black list or whitelist on who can see stuff published through it.  again at a personal level and potentially for publicly available ones as well.

I can also see the case for filters to act on things other than posts like follows, which might have subtly different uses than the "push" based filter I just mentioned.

Anyway that you look at it, filters should be as generically applicable to as many contexts as possible.  Its a good construct for streams of information,  its our grep in a way and I imagine them that way.  It would be cool to be able to use them to grep for posts and streams of other events and data like follows and then be able to act on the objects in the stream.  (unix for social)

Thats all for now.

**Comment by orianmarx** [comment]
We've rolled out muting, private messaging and stream filters so I'm closing this thread.
