### ISSUE TITLE
Don't call it REST, unless you want to argue about RESTfulness

### ISSUE THREAD

**Issue by johnsheehan** [appdotnet/api-spec#7]
From my experience it's not worth calling something REST, RESTful, REST-inspired, RESTlike or anything of the sort unless you want endless debates about the RESTfulness of your API. I think that would be a distraction to the cause.

Unless you're planning to fully embrace all of the REST constraints (hypermedia, versioned content types, etc) I would avoid it.

I propose: HTTP API or JSON API.

**Comment by berg** [comment]
I could not agree with you more. Going to update that right now.
