### ISSUE TITLE
How to get ID from Username

### ISSUE THREAD

**Issue by ghost** [appdotnet/api-spec#70]
Is there currently a method I am not seeing that makes it available to get a user ID from the username? I don't really want to expose the id for internal app links.

**Comment by tgvashworth** [comment]
+1. I'm currently scraping the user's page for [app.phuu.net](http://app.phuu.net).

**Comment by ghost** [comment]
You could also farm the usernames and store the lookup locally. If your app loads a user you don't know it could prompt for invite. But still I think we should get a simple Username -> ID. thoughts. http://appeio.com/?i=54147

**Comment by jdolitsky** [comment]
just added a function 'getIdByUsername to https://github.com/jdolitsky/AppDotNetPHP to workaround this issue

**Comment by chrishannah** [comment]
Where would you be using this?

**Comment by tgvashworth** [comment]
@cryptixdevelopment See all of the above... but just to give you a few examples: implementing a follow button where the only information you have is username; searching for a user if you're not sure they exist; retrieving a user from plain text/typed input...

**Comment by ghost** [comment]
The reason that prompted me, being able to easily have urls like http://appeio.com/username
