### ISSUE TITLE
Is there a limit to the # of API calls?

### ISSUE THREAD

**Issue by funkyboy** [appdotnet/api-spec#74]
I didn't find any mention of that.
Is there? Not yet? Will there be?

**Comment by markwilcox** [comment]
Somewhere in app.net discussion I think @berg mentioned it is currently set to 5000 per user per hour, although that's not necessarily a "final" number.

**Comment by JoshBlake** [comment]
@funkyboy @markwilcox It is here:
https://alpha.app.net/berg/post/49983

"berg:
@joshblake right now it's 5,000 calls per hour per user per app. happy to talk about raising that for other applications."

**Comment by abraham** [comment]
The current rate limit status is in API response headers.

```
X-RateLimit-Limit:5000
X-RateLimit-Remaining:4955
X-RateLimit-Reset:2934
```
