### ISSUE TITLE
Stream Filter for Geolocated Data

### ISSUE THREAD

**Issue by evansims** [appdotnet/api-spec#75]
We've been looking at the API spec and are getting quite excited about integrating ADN into our services; however, we rely heavily on geolocated data for content to be relevant. I noticed there is an allowance for [geopoints on the post object](https://github.com/appdotnet/api-spec/blob/master/resources/posts.md#retrieve-a-post) but there is no stated way of retrieving posts based on geofencing queries.

I'd like to propose an [additional filter](https://github.com/appdotnet/api-spec/blob/master/objects.md#filter) for [streams](https://github.com/appdotnet/api-spec/blob/master/resources/streams.md#retrieve-a-public-stream-of-real-time-posts) to support pulling posts within a configurable radius of a geopoint and/or a bounding box of lat and long.

**Comment by ralfr** [comment]
Doesn't this imply a more general - more powerful - requirement to allow filters to act on custom annotations as a universal "query language" to filter the stream? This would address many use cases including the one you're outlining.

**Comment by jschlesser** [comment]
I think that may be difficult to do.  In this case they would have to supply not only the data but also the algorithm to calculate not only query but also appropriate annotation indexes for geo based queries.   Its unbounded computation and io to provide a rich language like that.    

However, I dont see any reason why some enterprising person couldnt offer this as a service where they ingest the global stream and create geo indexes as well as other indexes for a rich query system.

Outside of that, if it were up to me I would implement geo specific services inside of the app.net infrastructure, its such a specific and possibly frequent use case.

**Comment by jschlesser** [comment]
@evansims I agree, geo should be considered fundamental these days.  Its expected and I know from first hand experience that it is much different than regular search indexing, its requires different data structures for efficient searching.  You can't just throw it into generic search technology and expect good results.
