### ISSUE TITLE
Liability, boring but necessary

### ISSUE THREAD

**Issue by jschlesser** [appdotnet/api-spec#77]
We might want to make an entire section for legal.

Dalton is asking people to build businesses on top of this, that is going to lead to some unhappy people at some point probably.  App.net needs to be clear what it is liable for and not liable for.  The unhappy people might be paying customers that got ripped off somehow or it might be a business that suffers some kind of negative impact etc...

Money is involved so best to think about these things now.  Note IANAL and am not offering any advice other than clear it up for us.

**Comment by fields** [comment]
See: https://github.com/appdotnet/api-spec/issues/73

**Comment by mthurman** [comment]
Let's move these kinds of issues to https://github.com/appdotnet/terms-of-service. Since this is a general issue, I'm not going to move it. Instead, feel free to open specific issues at the ToS repo.
