### ISSUE TITLE
Expand Subscriptions

### ISSUE THREAD

**Issue by jschlesser** [appdotnet/api-spec#78]
There are cases for services that could intercept things like app authorization against a database of known bad apps to support spam blocking services.   Think about building out hooks into all the aspects of service to allow more platform level services like this.  I can think of other cases too where it might be an auto authorization for things.   I think that this would be a higher level of security concern than allowing an app to post on my behalf.

**Comment by abitgone** [comment]
Presumably, if enough people legitimately and rightly complain about or flag a service, the API key for that particular service could simply be revoked.

With a minimum $100 entry to have an API key, chances are people – right now – aren't going to abuse it. Not saying that will be the case forever, but ADN having the ability to revoke any given API key for a breach of the TOS seems like enough of a safeguard for now.

**Comment by orianmarx** [comment]
I think @abitgone's response here is a pretty good summary of how we think about the issue. I'm closing this thread.
