### ISSUE TITLE
Post response should contain HTML version of text

### ISSUE THREAD

**Issue by johnsheehan** [appdotnet/api-spec#8]
https://github.com/appdotnet/api-spec/blob/110618639e633ece14d5d38b080af0a18558099f/objects.md#post-fields

To save devs the effort of having to write a text/entity processor for every framework, should just include a pre-processed one that is in HTML

**Comment by berg** [comment]
Sounds good.

**Comment by mxml-barmstrong** [comment]
Resolved!
