### ISSUE TITLE
Mute / Unmute Endpoint

### ISSUE THREAD

**Issue by ghost** [appdotnet/api-spec#83]
Does it exist undocumented in the API yet? Assuming that Alpha is using the API. :)

**Comment by mthurman** [comment]
It does exist in the API, I'm just still a little behind on updating docs :). It's essentially just like the follow endpoints (https://github.com/appdotnet/api-spec/blob/master/resources/users.md#follow-a-user)

`POST stream/0/users/[user_id]/mute`
`DELETE stream/0/users/[user_id]/mute`
both need the `follow` scope

`GET stream/0/users/me/muted` will return the current user's list of muted users (obviously you can't get the list of who other users have muted)

**Comment by ghost** [comment]
thank you sir

**Comment by mthurman** [comment]
The docs are updated: https://github.com/appdotnet/api-spec/blob/master/resources/users.md#mute-a-user
