### ISSUE TITLE
Add a "close thread" feature.

### ISSUE THREAD

**Issue by schwa** [appdotnet/api-spec#84]
That big white text area with the reply button is REALLY tempting for people like me with poor self control.

It could be conceivably really interesting if the originator of a threaded conversation was able close a thread and stop all further comments on that thread. It could be used as an acknowledgement that useful conversation on a topic has been exhausted and nothing is left but a reiteration of previous points.

After a thread has been closed people trying to reply could get POST errors and their reply would get converted into a new post that is not a reply - they would be free to refer to/link to the closed thread.

Of course this would have to be referred to as the "Godwin" feature.

**Comment by berg** [comment]
I mean this in the nicest possible way, but as it says in your App.net bio: "No." As in someone's gotta say it.

I hope that a Godwinning of a thread will be good enough... right?

**Comment by dquick-freelance** [comment]
Come on @berg - you're telling me it's not hilarious to post that and then close the issue? LOL

**Comment by berg** [comment]
It was meant as a joke. :)

We can still post on this thread, though. You can't stop me!
