### ISSUE TITLE
Localized Posts

### ISSUE THREAD

**Issue by chrishannah** [appdotnet/api-spec#87]
This is just a little idea that just came into my head that I thought might be useful.

I've seen a lot of people on Twitter that have to post twice because English is not their main language so they post something in English and then in Swedish for example.

So say you were German, with a mix of English/German speaking followers. Instead of posting something in one language or doing two posts, what if you could write a general post (English version) and then somehow add a localized version for German speakers? You would then have to choose a language option for your account.

I'm not sure if this would be a feature for the API or for a specific client, but it would be a nice addition.

**Comment by dch** [comment]
On 16 August 2012 11:28, Christopher Hannah notifications@github.comwrote:

> This is just a little idea that just came into my head that I thought
> might be useful.
> 
> I've seen a lot of people on Twitter that have to post twice because
> English is not their main language so they post something in English and
> then in Swedish for example.
> 
> So say you were German, with a mix of English/German speaking followers.
> Instead of posting something in one language or doing two posts, what if
> you could write a general post (English version) and then somehow add a
> localized version for German speakers? You would then have to choose a
> language option for your account.
> 
> I'm not sure if this would be a feature for the API or for a specific
> client, but it would be a nice addition.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/appdotnet/api-spec/issues/87.
> 
> There was a twitter client called nambu that automatically translated on
> the fly. It wasn't released as opensource but I think the issue is best
> dealt with client side.

Being able to set a user or post-specific language flag could be a good
idea tho, and then clients could filter as reqd, or server side optionally.

**Comment by cgiffard** [comment]
Interesting - and I think you'd just need two flags to do it. One flag to specify the language, and another to mark other as being mirror-content.

Then a client can automatically flick between different localisations of a given post, and replies to any of the posts' localisations are properly related/linked to all of them, so nobody's left out of the conversation.

**Comment by mthurman** [comment]
We have a core annotation for Posts indicating what language the post was written in which should be sufficient for now: http://developers.app.net/docs/meta/annotations/#language
