### ISSUE TITLE
Many Ideas

### ISSUE THREAD

**Issue by rickbenetti** [appdotnet/api-spec#88]
I'm know my english it's terrible.

Well I'm put down some ideas to help developer for this best idea @daltonc have:

<ul>
<li><b>Possibility to create a Groups:</b>
<ul>
<li>Like fan pages, but only to:</li>
<li>Assigned to Alpha users;</li>
<li>E-mails, like clients or friends just to see posts;</li>
<li>Create Groups links with relative URL e.g: alpha.app.net/rickbenetti/CuritibaFriends</li>
<li>Probably more detailed functions about that: https://github.com/appdotnet/api-spec/issues/33</li>
</ul>

</li>
<li><b>Localize Users:</b>

<ul>
<li>To resolve a uniqe username request I think to localize this users<br>
e.g: alpha.app.net/br/rickbenetti</li>
<li>Localizing the username we can do:
 <ul>
  <li>Find and talk with @daltonc using @us/dantonc</li>
  <li>Send a post all to users from japan e.g: "@jp/all my message here" and at global timeline at alpha.app.net/jp will be see.</li>
 </ul>
</li>
</ul>

</li>
<li><b>Language:</b>

<ul>
<li>Alpha Network at portuguese Brazil, Italian, Spanish, at some place to acess and propose a translate options</li>
</ul>

</li>
<li><b>Permissions</b>

<ul>
<li>With Groups will be nice If we can create a Personal Posts (for me, just to remember something or just to vent without making public</li>
<li>Post only a choosed Group</li>
<li>Post public</li>
</ul>

</li>
<li><b>Customization</b>

<ul>
<li>Possibilities to put different background or cover at my profile and Groups pages</li>
</ul>

</li>
</ul>

**Comment by orianmarx** [comment]
Thanks for these ideas. It makes it hard to track things placing these all under one "issue" so I'm going to close this and ask if you still want to propose these that you turn them into individual issues.
