### ISSUE TITLE
Avatar Size Feedback on Alpha

### ISSUE THREAD

**Issue by edent** [appdotnet/api-spec#93]
(This may be a bug on alpha.app.net)

When trying to upload a large image for my avatar, I get the error
"Avatar images must be square and less than 200x200 pixels."

That should read "less than or equal" as 200*200 is supported.

**Comment by kosso** [comment]
@edent I've been talking to them about this for a while. They're working on the ability to resize/specify image dimensions with  w= and h= 

It's high up on their list.

**Comment by mthurman** [comment]
These error messages in Alpha should now be updated.
