### ISSUE TITLE
Page numbering for posts

### ISSUE THREAD

**Issue by markwilcox** [appdotnet/api-spec#97]
Support longer form content (segmentation and re-assembly for bigger data blocks in general) by having a page numbering system - either as a field(s) or well-know annotation.

Make sure it's possible to filter for at least 1st post in a multi-part post only.

Have a page number limit that enables short blogs but discourages use of the mechanism for sending files.

Devs are going to do this anyway, might as well include an official and re-usable mechanism rather than have multiple apps re-invent the wheel.

**Comment by orianmarx** [comment]
Actually this is one of those things we are going to let devs do if they want to but we're not going to encourage it :)
