### ISSUE TITLE
REQ: Pagination for follower/following lists

### ISSUE THREAD

**Issue by kosso** [appdotnet/api-spec#98]
There is currently no pagination on https://alpha-api.app.net/stream/0/users/[user_id]/following|followers

This fails to consider the 'Scoble/Fry factor'. :)

**Comment by kosso** [comment]
The followers / following data supplied by the API very much needs to be ordered by 'date followed' and paginated. 

Currently, even in these relatively early numbers, having a mobile download a list of a few hundred User objects at a time is proving to be unwieldy.

But the main issue is the random ordering which currently makes no sense to the developer or the end user of a client.

**Comment by mthurman** [comment]
We just rolled out a migration for this: https://github.com/appdotnet/api-spec/blob/master/migrations.md#current-migrations and https://github.com/appdotnet/api-spec/blob/master/resources/users.md#list-users-following-a-user

**Comment by kosso** [comment]
Thanks.
Does it require the new data envelope too?
(I'm assuming it does, to provide a 'more' value (if there are more))

Kosso

**Comment by mxml-barmstrong** [comment]
You don't need to have envelopes enabled in order to use the pagination parameters, but if you don't have them, it is up to you to figure out what the IDs are and whether there are more. As a result, it is highly recommended you use response envelopes.

**Comment by kosso** [comment]
No problem. Agreed. Make much more sense to do that first ;)

Thanks again.
